'use strict';
const assert=require('node:assert/strict');
const DATA=require('../lc05-data.js');
const {GameEngine,seededRandom}=require('../lc05-engine.js');
const tests=[];const test=(n,f)=>tests.push({n,f});const make=(seed=1)=>new GameEngine({random:seededRandom(seed),data:DATA});

test('LIVING-CITY-05 startet mit Schema 6',()=>{const e=make();assert.equal(e.state.schema,6);assert.equal(e.state.version,'0.11.1-living-city-05a');assert.equal(e.data.interiorScenes['location.bunker.main'].title,'Kommandozentrale');});
test('Startercrew erhält Stress, Moral und drei Beziehungen',()=>{const e=make();assert.equal(e.state.gang.length,3);e.state.gang.forEach((m)=>{assert.ok(Number.isFinite(m.stress));assert.ok(Number.isFinite(m.morale));});assert.equal(e.getCrewRelationsOverview().length,3);});
test('Beziehungslabels decken das Spektrum ab',()=>{const e=make();assert.equal(e.relationLabel(90),'Verbündet');assert.equal(e.relationLabel(70),'Eng verbunden');assert.equal(e.relationLabel(52),'Stabil');assert.equal(e.relationLabel(20),'Angespannt');assert.equal(e.relationLabel(10),'Zerwürfnis');});
test('Aussprache verbessert Beziehung und verbraucht einen Zug',()=>{const e=make(2),[a,b]=e.state.gang,before=e.getCrewRelation(a.id,b.id).value,turn=e.state.turn;e.state.resources.money=9999;const r=e.runCrewInteraction(a.id,b.id,'talk');assert.equal(r.ok,true);assert.equal(e.state.turn,turn+1);assert.ok(e.getCrewRelation(a.id,b.id).value>before);assert.equal(e.state.stats.crewInteractions,1);});
test('Crewinteraktion besitzt Cooldown',()=>{const e=make(3),[a,b]=e.state.gang;e.state.resources.money=9999;assert.equal(e.runCrewInteraction(a.id,b.id,'plan').ok,true);const r=e.runCrewInteraction(a.id,b.id,'talk');assert.equal(r.ok,false);assert.match(r.reason,/Abstand/i);});
test('Erholen senkt Stress im autonomen Zyklus',()=>{const e=make(4),m=e.state.gang[0];m.stress=70;e.assignCrewTask(m.id,'task.rest');e.advanceTurn();assert.ok(m.stress<70);});
test('Gemeinsamer Dauerauftrag kann Beziehung stärken',()=>{const e=make(5),[a,b]=e.state.gang;a.assignment={taskId:'task.scout',targetId:'location.market.black',cycles:0,progress:0};b.assignment={taskId:'task.scout',targetId:'location.market.black',cycles:0,progress:0};e.state.turn=1;const before=e.getCrewRelation(a.id,b.id).value;e.advanceTurn();assert.ok(e.getCrewRelation(a.id,b.id).value>=before);});
test('Innenansicht liefert Ort, Hotspots und lokale Werte',()=>{const e=make(),s=e.getInterior('location.casino.9909');assert.equal(s.title,'Casino 9909');assert.equal(s.hotspots.length,3);assert.ok(Number.isFinite(s.control));assert.equal(s.ambient.label,'Casino-Schimmer');});
test('Nicht speziell definierter Ort erhält Fallback-Innenansicht',()=>{const e=make(),loc=e.data.world.locations.find((x)=>!e.data.interiorScenes[x.id]),s=e.getInterior(loc.id);assert.ok(s.title);assert.ok(s.hotspots.length>=2);});
test('Innenansicht wird statistisch erfasst',()=>{const e=make(),before=e.state.stats.interiorsOpened;e.recordInteriorOpen();assert.equal(e.state.stats.interiorsOpened,before+1);});
test('Auftragsannahme aktiviert Briefing',()=>{const e=make(8),m=e.state.missions.offers[0],r=e.acceptMission(m.id);assert.equal(r.ok,true);const active=e.state.missions.active[0];assert.equal(active.briefingPending,true);assert.ok(e.getMissionBriefing(active.id).advisor);});
test('Sicheres Briefing verlängert Frist und ist einmalig',()=>{const e=make(9),m=e.state.missions.offers[0];e.acceptMission(m.id);const a=e.state.missions.active[0],before=a.deadline;e.resolveMissionBriefing(a.id,'careful');assert.equal(a.deadline,before+2);assert.equal(e.state.stats.briefings,1);assert.equal(e.resolveMissionBriefing(a.id,'bold').ok,false);});
test('Mutiges Briefing erhöht Geldbelohnung und Spannung',()=>{const e=make(10),m=e.state.missions.offers.find((x)=>x.reward?.money);e.acceptMission(m.id);const a=e.state.missions.active.find((x)=>x.id===m.id),money=a.reward.money,tension=e.state.director.tension;e.resolveMissionBriefing(a.id,'bold');assert.ok(a.reward.money>money);assert.ok(e.state.director.tension>=tension);});
test('Team-Briefing stärkt Crewbindung',()=>{const e=make(11),m=e.state.missions.offers[0];e.acceptMission(m.id);const info=e.getMissionBriefing(m.id),before=e.getCrewRelation(info.advisor.id,info.partner.id).value;const r=e.resolveMissionBriefing(m.id,'team');assert.equal(r.ok,true);assert.ok(e.getCrewRelation(info.advisor.id,info.partner.id).value>before);});
test('Kartenebene akzeptiert nur bekannte Werte',()=>{const e=make();assert.equal(e.setMapLayer('economy').ok,true);assert.equal(e.state.preferences.mapLayer,'economy');assert.equal(e.setMapLayer('x').ok,false);});
test('Atmosphäre kann an- und ausgeschaltet werden',()=>{const e=make();e.setAmbientEnabled(true);assert.equal(e.state.preferences.ambient,true);e.setAmbientEnabled(false);assert.equal(e.state.preferences.ambient,false);});
test('Schema-5-Spielstand wird vollständig auf Schema 6 ergänzt',()=>{const old=make().getSnapshot();old.schema=5;old.version='0.10.1-living-city-04a';delete old.crewRelations;delete old.preferences;old.gang.forEach((m)=>{delete m.stress;delete m.morale;});const e=new GameEngine({state:old,random:seededRandom(12),data:DATA});assert.equal(e.state.schema,6);assert.ok(e.state.crewRelations);assert.ok(e.state.preferences);assert.ok(Number.isFinite(e.state.gang[0].stress));});

test('Ausgeschiedene Crew hinterlässt keine verwaisten Beziehungen',()=>{const e=make(13),gone=e.state.gang.pop();e.ensureCrewRelations();assert.ok(e.getCrewRelationsOverview().every((r)=>r.a!==gone.id&&r.b!==gone.id));});
test('Briefing-Modifikatoren wirken auf den Director und klingen ab',()=>{const e=make(14),m=e.state.missions.offers[0];e.acceptMission(m.id);e.resolveMissionBriefing(m.id,'bold');const boosted=e.getDirectorSummary().tension,mod=e.state.directorModifiers.tension;assert.ok(mod>0);e.advanceTurn();assert.ok(Math.abs(e.state.directorModifiers.tension)<Math.abs(mod));assert.ok(Number.isFinite(boosted));});
test('1200 Züge bleiben numerisch stabil',()=>{const e=make(2026);e.state.resources.money=1e6;e.state.resources.supplies=1e5;e.state.bank.balance=5e5;for(let i=0;i<1200;i+=1){e.advanceTurn();for(const m of e.state.gang){assert.ok(Number.isFinite(m.stress)&&m.stress>=0&&m.stress<=100);assert.ok(Number.isFinite(m.morale)&&m.morale>=0&&m.morale<=100);}for(const r of e.getCrewRelationsOverview()){assert.ok(r.value>=0&&r.value<=100);}assert.ok(e.state.cityEvents.length<=2);}});
let passed=0;for(const t of tests){try{t.f();passed++;}catch(err){console.error('FAIL:',t.n);throw err;}}console.log(`PASS: LIVING-CITY-05 Engine – ${passed}/${tests.length} Tests erfolgreich.`);
