'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');const path=require('node:path');
const root=path.join(__dirname,'..'),repo=path.join(root,'..');
const read=(f)=>fs.readFileSync(f,'utf8');
const html=read(path.join(root,'index.html'));
const css=read(path.join(root,'lc05b.css'));
const ui=read(path.join(root,'lc05b-ui.js'));
const refresh=read(path.join(root,'ui-refresh.js'));
assert.ok(html.includes('id="focusDashboard"'),'Oberes Aufgaben-Dashboard fehlt.');
assert.ok(html.includes('id="mapWorkbench"')&&html.includes('id="helpDock"'),'Karten-Arbeitsbereich oder Hilfe-Dock fehlt.');
assert.ok(html.indexOf('id="mapStage"')<html.indexOf('id="helpDock"'),'Hilfe muss neben/nach der Karte liegen, nicht in ihr.');
assert.ok(html.includes('id="mapDirectTargets"'),'Direktziele fehlen an der Karte.');
assert.ok(html.includes('id="cityMap"')&&html.includes('tabindex="0"'),'Karte muss per Tastatur fokussierbar sein.');
assert.ok(css.includes('.map-workbench.help-open{grid-template-columns')&&css.includes('#helpDialog{display:none!important}'),'Nicht überdeckende Hilfe ist nicht vertraglich abgesichert.');
assert.ok(css.includes('@container(max-width:760px)')&&css.includes('@media(max-width:1120px)')&&css.includes('@media(max-width:820px)')&&css.includes('@media(max-width:560px)'),'Mehrstufige responsive Anpassung fehlt.');
assert.ok(ui.includes("addEventListener('pointerdown'")&&ui.includes("addEventListener('pointermove'")&&ui.includes("addEventListener('wheel'")&&ui.includes('setPointerCapture'),'Freies Maus-Panning/Zoom fehlt.');
assert.ok(ui.includes("'arrowleft'")&&ui.includes("'a'")&&ui.includes("'arrowup'")&&ui.includes("k==='m'")&&ui.includes("k==='h'")&&ui.includes("k==='r'"),'Karten-/Hilfe-/Reise-Tastatursteuerung fehlt.');
assert.ok(ui.includes('renderDashboard')&&ui.includes('primaryTask')&&ui.includes('renderDirectTargets'),'Aufgaben- oder Reiseführung fehlt.');
assert.ok(ui.includes('cloneNode(true)')&&ui.includes('replaceWith'),'Alter modaler Hilfe-Handler wird nicht sicher entkoppelt.');
assert.ok(!ui.includes('MutationObserver'),'LC05B darf keinen globalen DOM-Observer einführen.');
assert.ok(refresh.includes('LIVING_CITY_05B_UI?.render?.()'),'Zentraler Refresh aktualisiert LC05B nicht.');
assert.ok(refresh.includes("#mapZoomOut,#mapZoomReset,#mapZoomIn")&&refresh.includes('LIVING_CITY_05B_UI?.zoomIn?.()')&&refresh.includes('LIVING_CITY_05B_UI?.zoomOut?.()')&&refresh.includes('LIVING_CITY_05B_UI?.fitMap?.()')&&refresh.includes("event.target?.closest?.('#cityMap')")&&refresh.includes('if(mapViewport)return'),'Letzter UI-Arbiter muss sichtbare Zoomtasten kanonisch anwenden und reine Karten-Pan-Aktionen vom Voll-Render trennen.');
const order=['lc05-ui.js','lc05b-ui.js','ui-refresh.js'].map((n)=>html.indexOf(`src="${n}"`));
assert.ok(order.every((v)=>v>=0)&&order[0]<order[1]&&order[1]<order[2],'LC05B-Scriptreihenfolge falsch.');
console.log('PASS: LIVING-CITY-05B Vertrag – Hilfe-Dock, Aufgaben-Dashboard, Reise, Zoom/Pan, Tastatur und Responsive Design geprüft.');

assert.ok(ui.includes('function zoomCenter')&&ui.includes('installZoomControls')&&ui.includes("#mapZoomOut,#mapZoomReset,#mapZoomIn")&&ui.includes("zoomIn:()=>zoomCenter(1.22)"),'Kartenzoom muss robust über den SVG-Mittelpunkt und zentrale Steuerung gebunden sein.');
