'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');const path=require('node:path');
const root=path.join(__dirname,'..');const repo=path.join(root,'..');const read=(f)=>fs.readFileSync(f,'utf8');
const html=read(path.join(root,'index.html')),data=read(path.join(root,'lc06-data.js')),engine=read(path.join(root,'lc06-engine.js')),ui=read(path.join(root,'lc06-ui.js')),css=read(path.join(root,'lc06.css')),bootstrap=read(path.join(root,'lc06-bootstrap.js')),refresh=read(path.join(root,'ui-refresh.js'));
assert.ok(html.includes('lc06-ui.js')&&html.includes('lc06.css'),'LC06-Funktionsschicht fehlt im aktuellen sichtbaren UI.');
assert.ok(html.includes('id="coachRail"')&&html.includes('id="lc06AudioButton"'),'Coach-Leiste oder Klangschalter fehlt.');
const order=['lc05-data.js','lc06-data.js','lc05-engine.js','lc06-engine.js','lc05-bootstrap.js','lc06-bootstrap.js','app.js','lc05-ui.js','lc05b-ui.js','lc06-ui.js','ui-refresh.js'].map((n)=>html.indexOf(`src="${n}"`));
assert.ok(order.every((v)=>v>=0)&&order.every((v,i)=>i===0||order[i-1]<v),'LC06-Scriptreihenfolge ist nicht deterministisch.');
assert.ok(html.indexOf('lc05b.css')<html.indexOf('lc06.css'),'LC06-CSS muss nach 05B geladen werden.');
assert.ok(data.includes('interiorActions')&&data.includes('dialogues')&&data.includes('audioPresets'),'LC06-Datenvertrag unvollständig.');
assert.ok(engine.includes('performInteriorAction')&&engine.includes('chooseDialogue')&&engine.includes('setAudioMixer')&&engine.includes('getGuidance')&&engine.includes('getCombatDecisionGuide'),'LC06-Enginevertrag unvollständig.');
assert.ok(ui.includes('renderInteriorEnhancement')&&ui.includes('renderDialogue')&&ui.includes('renderAudioDock')&&ui.includes('renderCombatEnhancement')&&ui.includes('renderGuide'),'LC06-UI-Systeme fehlen.');
assert.ok(ui.includes("k==='g'")&&ui.includes("k==='i'")&&ui.includes("k==='k'")&&ui.includes('event.altKey'),'LC06-Tastaturführung unvollständig.');
assert.ok(ui.includes("renderScene?.(activeInteriorId);renderInteriorEnhancement();"),'Innenraumaktionen müssen beim Tastatur-Öffnen atomar mit dem Dialog gerendert werden.');
assert.ok(ui.includes("activeInteriorId=t.dataset.openInterior;renderInteriorEnhancement();setTimeout(renderInteriorEnhancement,0);"),'Innenraumaktionen brauchen beim Klick einen synchronen Render plus robusten Nachlauf.');
assert.ok(!ui.includes('MutationObserver'),'LC06 darf keinen globalen DOM-Observer einführen.');
assert.ok(ui.includes("[data-crew-interaction]")&&ui.includes('stopImmediatePropagation'),'LC06 muss Crewinteraktionen vor dem alten Vollseiten-Reload abfangen.');
assert.ok(css.includes('.coach-rail')&&css.includes('.interior-action-grid')&&css.includes('.audio-dock')&&css.includes('.lc06-combat-coach'),'LC06-Visualvertrag unvollständig.');
assert.ok(css.includes('@media(max-width:820px)')&&css.includes('@media(max-width:560px)'),'LC06-Responsive-Abstufungen fehlen.');
assert.ok(bootstrap.includes('pppoppi-bunkerwahrheit-html-v0120')&&bootstrap.includes('__livingCity06Patched'),'LC06-Speichermigration fehlt.');
assert.ok(refresh.includes('LIVING_CITY_06_UI?.render?.()'),'Zentraler Refresh aktualisiert LC06 nicht.');
assert.equal((css.match(/\{/g)||[]).length,(css.match(/\}/g)||[]).length,'LC06-CSS-Klammern unausgeglichen.');
console.log('PASS: LIVING-CITY-06 Vertrag – Führung, Innenräume, Dialoge, Klang, Kampf, Speicher und Tastatur geprüft.');
