'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');const path=require('node:path');
const root=path.join(__dirname,'..'),repo=path.join(root,'..');const read=(f)=>fs.readFileSync(f,'utf8');
const html=read(path.join(root,'index.html')),data=read(path.join(root,'lc07-data.js')),engine=read(path.join(root,'lc07-engine.js')),ui=read(path.join(root,'lc07-ui.js')),css=read(path.join(root,'lc07.css')),bootstrap=read(path.join(root,'lc07-bootstrap.js')),refresh=read(path.join(root,'ui-refresh.js')),e2e=read(path.join(repo,'tools/chrome_e2e.py'));
assert.ok(html.includes('lc07-data.js')&&html.includes('lc07-engine.js')&&html.includes('lc07-ui.js'),'LC07-Funktionsschicht fehlt aus der aktuellen Fassung.');
const order=['lc06-data.js','lc07-data.js','lc06-engine.js','lc07-engine.js','lc06-bootstrap.js','lc07-bootstrap.js','app.js','lc06-ui.js','lc07-ui.js','ui-refresh.js'].map(n=>html.indexOf(`src="${n}"`));
assert.ok(order.every(v=>v>=0)&&order.every((v,i)=>i===0||order[i-1]<v),'LC07-Scriptreihenfolge falsch.');
assert.ok(html.indexOf('lc06.css')<html.indexOf('lc07.css'),'LC07-CSS muss zuletzt geladen werden.');
assert.ok(data.includes('dlg.station.dispatch')&&data.includes('dlg.archive.keeper')&&data.includes('dlg.casino.host')&&data.includes('dlg.oldtown.connector'),'Neue Folgeketten fehlen.');
assert.ok(engine.includes('storyFlags')&&engine.includes('storyConsequences')&&engine.includes('optionAllowed')&&engine.includes('getStorySummary'),'LC07-Enginevertrag unvollständig.');
assert.ok(ui.includes('story-strip')&&ui.includes('data-audio-ducking')&&ui.includes('playUiTone')&&ui.includes("'1':'attack'")&&ui.includes('pagehide'),'LC07-UI-/Audio-Härtung unvollständig.');
assert.ok(!ui.includes('MutationObserver'),'LC07 darf keinen globalen DOM-Observer einführen.');
assert.ok(css.includes('@media(min-width:1280px) and (min-height:720px)')&&css.includes('.lc07-consequence-note'),'LC07-Desktop-Fit oder Folgevisualisierung fehlt.');
assert.ok(css.includes('@media(min-width:1180px) and (max-height:900px)')&&css.includes('min-height:260px!important')&&css.includes('.top-kpis{display:none}'),'LC07-Kompakt-Desktop-Gate für 1280×720 fehlt.');
assert.ok(css.includes('.map-workbench.help-open{grid-template-columns:minmax(430px,1fr) minmax(210px,230px)')&&css.includes('.map-workbench.help-open>.help-dock{grid-column:2;grid-row:2'), 'LC07-Hilfedock muss im Desktop neben der nutzbaren Karte bleiben.');
assert.ok(bootstrap.includes('pppoppi-bunkerwahrheit-html-v0130')&&bootstrap.includes('__livingCity07Patched'),'LC07-Speichermigration fehlt.');
assert.ok(refresh.includes('LIVING_CITY_07_UI?.render?.()'),'Zentraler Refresh aktualisiert LC07 nicht.');
assert.ok(e2e.includes('Google Chrome')&&e2e.includes('VIEWPORTS = [(1280, 720), (1366, 768), (1600, 900)]'),'Echter Chrome-Desktop-E2E-Vertrag fehlt.');
assert.ok(e2e.includes('Hilfe überdeckt die Karte')&&e2e.includes('Kartenzoom')&&e2e.includes('combat_decision.png'),'E2E-Nutzerpfade der LC07-Basisschicht unvollständig.');
assert.ok(e2e.includes('map_rect[\"width\"]')&&!e2e.includes('map_rect[\"w\"]'),'E2E-Hilfedock-Rechteckvertrag verwendet inkonsistente Schlüssel.');
assert.equal((css.match(/\{/g)||[]).length,(css.match(/\}/g)||[]).length,'LC07-CSS-Klammern unausgeglichen.');
console.log('PASS: LIVING-CITY-07 Vertrag – Chrome-E2E, Folgeketten, Innenräume, Audio, Kampf und Speicher geprüft.');
