const fs=require('fs');const path=require('path');const assert=require('assert');const root=path.join(__dirname,'..');const read=(f)=>fs.readFileSync(path.join(root,f),'utf8');
const html=read('index.html'),ui=read('lc10-ui.js'),css=read('lc10.css'),boot=read('lc10-bootstrap.js'),data=read('lc10-data.js'),engine=read('lc10-engine.js'),refresh=read('ui-refresh.js');
assert.ok(html.includes('0.16.0 LIVING-CITY-10'));
['lc10-data.js','lc10-engine.js','lc10-bootstrap.js','lc10-ui.js','lc10.css'].forEach((x)=>assert.ok(html.includes(x),x));
assert.ok(data.includes("schema:11")&&data.includes('initiativeChoices')&&data.includes('districtBands'));
assert.ok(engine.includes('getCityTrends')&&engine.includes('resolveCrewInitiative')&&engine.includes('3000')===false);
assert.ok(boot.includes('html-v0160')&&boot.includes('recovery-v0160'));
assert.ok(ui.includes('Stadtlage')&&ui.includes("e.key.toLowerCase()==='l'")&&ui.includes('data-lc10-initiative'));
assert.ok(css.includes('lc10-districts')&&css.includes('lc10-initiatives')&&css.includes('lc10-history'));
assert.ok(refresh.includes('LIVING_CITY_10_UI'));
assert.ok(html.indexOf('lc10-data.js')<html.indexOf('lc10-engine.js'));assert.ok(html.indexOf('lc10-engine.js')<html.indexOf('app.js'));assert.ok(html.indexOf('lc10-bootstrap.js')<html.indexOf('app.js'));assert.ok(html.indexOf('lc10-ui.js')>html.indexOf('app.js'));
console.log('PASS: LIVING-CITY-10 Vertrag – Bezirksdynamik, Crew-Eigeninitiative, Stadtlage, v0160 und Startreihenfolge geprüft.');
