const assert=require('assert');const DATA=require('../lc10-data.js');const API=require('../lc10-engine.js');let pass=0;
function test(name,fn){try{fn();pass++;}catch(error){console.error(`FAIL: ${name}`);throw error;}}
function engine(){return new API.GameEngine();}
test('Version und Schema',()=>{assert.equal(DATA.version,'0.16.0-living-city-10');assert.equal(DATA.schema,11);assert.equal(API.VERSION,DATA.version);assert.equal(API.SCHEMA,11);});
test('Alle Bezirke erhalten Dynamik',()=>{const e=engine();assert.equal(Object.keys(e.state.districtDynamics).length,DATA.world.locations.length);DATA.world.locations.forEach((l)=>{const d=e.getDistrictDynamics(l.id);['pressure','stability','opportunity','momentum'].forEach((k)=>assert.ok(Number.isFinite(d[k]),`${l.id}:${k}`));});});
test('Dynamik bleibt im Wertebereich',()=>{const e=engine();for(let i=0;i<80;i++)e.advanceTurn();e.getCityTrends().districts.forEach((d)=>{assert.ok(d.pressure>=0&&d.pressure<=100);assert.ok(d.stability>=0&&d.stability<=100);assert.ok(d.opportunity>=0&&d.opportunity<=100);assert.ok(d.momentum>=-15&&d.momentum<=15);});});
test('Stadttrends benennen Druck und Dynamik',()=>{const e=engine(),t=e.getCityTrends();assert.equal(t.districts.length,DATA.world.locations.length);assert.ok(t.pressure.title);assert.ok(t.improving.title);});
test('Crew-Initiative entsteht deterministisch',()=>{const e=engine();while(e.state.turn<4)e.advanceTurn();assert.ok(e.getCrewInitiatives().length>=1);const i=e.getCrewInitiatives()[0];assert.ok(i.memberName&&i.locationTitle&&i.choices.length===3);});
test('Unterstützen löst Initiative',()=>{const e=engine();while(e.state.turn<4)e.advanceTurn();const i=e.getCrewInitiatives()[0],before=e.state.stats.crewInitiativesResolved,r=e.resolveCrewInitiative(i.id,'support');assert.equal(r.ok,true);assert.equal(e.state.stats.crewInitiativesResolved,before+1);assert.ok(!e.getCrewInitiatives().some((x)=>x.id===i.id));});
test('Beobachten erhöht Aufklärung',()=>{const e=engine();while(e.state.turn<4)e.advanceTurn();const i=e.getCrewInitiatives()[0],before=e.getDistrict(i.locationId).intel;e.resolveCrewInitiative(i.id,'observe');assert.ok(e.getDistrict(i.locationId).intel>=before);});
test('Umlenken senkt Unruhe',()=>{const e=engine();while(e.state.turn<4)e.advanceTurn();const i=e.getCrewInitiatives()[0],before=e.getDistrict(i.locationId).unrest;e.resolveCrewInitiative(i.id,'redirect');assert.ok(e.getDistrict(i.locationId).unrest<=before);});
test('Initiative wird journalisiert',()=>{const e=engine();while(e.state.turn<4)e.advanceTurn();const i=e.getCrewInitiatives()[0];e.resolveCrewInitiative(i.id,'support');assert.ok(e.getDecisionJournal(20).some((x)=>x.kind==='initiative'));});
test('LC10 korrigiert Crew-Puls auf state.gang',()=>{const e=engine();e.state.gang.forEach((m)=>{m.stress=80;m.morale=20;});const p=e.getCityPulse();assert.ok(p.avgStress>=70);assert.ok(p.avgMorale<=30);});
test('Migration ergänzt Schema 11 und Dynamik',()=>{const old=engine().state;delete old.districtDynamics;delete old.crewInitiatives;old.schema=10;old.version='0.15.0-living-city-09';const e=new API.GameEngine({state:old});assert.equal(e.state.schema,11);assert.equal(e.state.version,DATA.version);assert.equal(Object.keys(e.state.districtDynamics).length,DATA.world.locations.length);});
test('3000-Zug-Langlauf bleibt numerisch stabil',()=>{const e=engine();for(let i=0;i<3000;i++){e.advanceTurn();if(e.getCrewInitiatives().length)e.resolveCrewInitiative(e.getCrewInitiatives()[0].id,['support','observe','redirect'][i%3]);}const t=e.getCityTrends();assert.equal(t.districts.length,12);t.districts.forEach((d)=>Object.values(d).forEach((v)=>{if(typeof v==='number')assert.ok(Number.isFinite(v));}));});
console.log(`PASS: LIVING-CITY-10 Engine – ${pass}/${pass} Tests erfolgreich.`);
