const fs=require('fs');const path=require('path');const assert=require('assert');const root=path.join(__dirname,'..');const read=(f)=>fs.readFileSync(path.join(root,f),'utf8');
const html=read('index.html'),css=read('lc11-visual-polish-6.css')+read('lc11-visual-polish-6b.css')+read('lc11-visual-polish-6c.css')+read('lc11-visual-polish-6d.css'),closeCss=read('lc11-close-control.css'),ui=read('lc11-ui.js'),data=read('lc11-data.js');
assert.ok(html.includes('lc11-visual-polish-6.css')&&html.includes('lc11-visual-polish-6b.css')&&html.includes('lc11-visual-polish-6c.css')&&html.includes('lc11-close-control.css'));
assert.ok(html.indexOf('lc11-visual-polish-5b.css')<html.indexOf('lc11-visual-polish-6.css'));
assert.ok(html.indexOf('lc11-visual-polish-6.css')<html.indexOf('lc11-visual-polish-6b.css'));
assert.ok(html.indexOf('lc11-visual-polish-6b.css')<html.indexOf('lc11-visual-polish-6c.css'));
assert.ok(html.indexOf('lc11-visual-polish-6c.css')<html.indexOf('lc11-close-control.css'),'Kritischer Close-Control-Layer muss nach Visual Polish VI laden.');
assert.ok(closeCss.includes('@import url("lc11-visual-polish-6d.css");'),'VI-E/F/G/H muss vor dem finalen Close-Control-Regelsatz importiert werden.');
assert.ok(html.includes('0.17.6 LIVING-CITY-11 VISUAL-POLISH-VI'));
assert.ok(data.includes("version:'0.17.6-living-city-11-visual-polish-6'"));assert.ok(ui.includes('0.17.6 · Schema 12'));
['Visual Polish VI-E · Kartenleseschlüssel','Visual Polish VI-F · Bezirksmarker als kompakte Lageinstrumente','Visual Polish VI-G · Straßen-, Bahn- und Routenhierarchie','.route.reachable{','.train-route.reachable{','.route.planned{','.route.chosen,.train-route.chosen{','@keyframes vp6RouteFlow','Visual Polish VI-H · Ereignis- und Gefahrenlagen ohne zusätzliche Kartenebene','.district-node.event-hot .zone{','.district-node.event-hot .node-core{','.district-node.pressure-watch .zone{','.district-node.pressure-critical .zone{','.district-node.event-hot.pressure-critical .zone{','@keyframes vp6EventPulse'].forEach((x)=>assert.ok(css.includes(x),x));
assert.ok(css.includes('button:focus-visible')&&css.includes('.district-node:focus-visible'),'Fokuszustände müssen sichtbar bleiben.');
assert.ok(!css.includes('pointer-events:auto'),'Visual Polish VI darf keine eigene aktive Interaktionsebene erzwingen.');
const viE=read('lc11-visual-polish-6d.css');assert.ok(!/(^|[;{])\s*(padding|min-height|min-width|max-height|max-width|grid-template(?:-areas|-columns|-rows)?)\s*:/m.test(viE),'VI-E/F/G/H darf keine Layoutmaße oder Grid-Geometrie setzen.');
assert.ok(viE.includes('@media(prefers-reduced-motion:reduce){.district-node.event-hot .node-core{animation:none!important}}'),'VI-H Ereignispuls muss Reduced Motion respektieren.');
const pointerAuto=(closeCss.match(/pointer-events:auto/g)||[]).length;assert.equal(pointerAuto,1,'Nur Close-Control darf pointer-events:auto explizit setzen.');assert.ok(closeCss.includes('z-index:120!important')&&closeCss.includes('visibility:visible!important'));
console.log('PASS: Visual-Polish VI – Kartenlage, Bezirksmarker, Routenhierarchie, Ereignis-/Gefahrenlagen, Innenräume, Kampf und Reduced-Motion geprüft.');
