const assert=require('assert');const DATA=require('../lc11-data.js');const API=require('../lc11-engine.js');let pass=0;
function test(name,fn){try{fn();pass++;}catch(error){console.error('FAIL:',name);throw error;}}
function engine(random=()=>0.17){return new API.GameEngine({random});}
test('Version und Schema',()=>{assert.equal(DATA.version,'0.17.5-living-city-11-visual-polish-5');assert.equal(DATA.schema,12);assert.equal(API.SCHEMA,12);});
test('LC11 Zustand wird vollständig angelegt',()=>{const e=engine();assert.ok(e.state.casinoFloor);assert.ok(Array.isArray(e.state.externalTravelHistory));assert.ok(Array.isArray(e.state.trainingHistory));assert.equal(Object.keys(e.state.casinoFloor.jackpots).length,DATA.casino.slotMachines.length);});
test('Casino-Automat ist spielbar und zählt Session',()=>{const e=engine(()=>0.2);e.state.currentLocationId='location.casino.9909';e.state.resources.money=1000;const r=e.spinSlot(DATA.casino.slotMachines[0].id,10);assert.equal(r.ok,true);assert.equal(e.getCasinoFloor().session.spins,1);});
test('Poker läuft bis Showdown und zählt Session',()=>{const e=engine(()=>0.31);e.state.currentLocationId='location.casino.9909';e.state.resources.money=1000;assert.equal(e.startPoker(50).ok,true);e.togglePokerHold(0);assert.equal(e.drawPoker().ok,true);const r=e.finishPoker();assert.equal(r.ok,true);assert.equal(e.getCasinoFloor().session.pokerHands,1);});
test('Casino-Aufgabe kann nach Ziel abgeholt werden',()=>{const e=engine(()=>0.23);e.state.currentLocationId='location.casino.9909';e.state.resources.money=1000;for(let i=0;i<3;i++)e.spinSlot(DATA.casino.slotMachines[0].id,5);const c=e.getCasinoFloor().challenges.find((x)=>x.id==='slots-three');assert.equal(c.complete,true);const before=e.state.resources.money,r=e.claimCasinoChallenge('slots-three');assert.equal(r.ok,true);assert.equal(e.state.resources.money,before+c.reward);});
test('Kampfsporttraining erzeugt Rangfortschritt und Historie',()=>{const e=engine();e.state.currentLocationId='location.blocks.east';e.state.resources.money=5000;const member=e.state.gang[0],r=e.trainMemberProgram(member.id,'art.boxing','intense');assert.equal(r.ok,true);assert.equal(e.state.stats.trainingSessions,1);assert.equal(e.state.trainingHistory.length,1);assert.ok(member.martialArts.some((x)=>x.artId==='art.boxing'));});
test('Schutzkleidung besitzt Zustand und kann gewartet werden',()=>{const e=engine();e.state.currentLocationId='location.market.black';e.state.resources.money=5000;const b=e.buyGear('gear.vest');assert.equal(b.ok,true);const item=e.state.inventory.find((x)=>x.id===b.item.id);item.condition=52;const r=e.serviceGear(item.id);assert.equal(r.ok,true);assert.equal(item.condition,100);});
test('Abgenutzte Ausrüstung liefert geringeren Bonus',()=>{const e=engine();e.state.currentLocationId='location.market.black';e.state.resources.money=5000;const b=e.buyGear('gear.vest'),m=e.state.gang[0];e.equipGear(b.item.id,m.id);const fresh=e.getMemberGearBonuses(m.id).defense;e.state.inventory[0].condition=40;const worn=e.getMemberGearBonuses(m.id).defense;assert.ok(worn<fresh);});
test('Fernreise kostet, dauert und wird protokolliert',()=>{const e=engine();e.state.currentLocationId='location.station.ghost';e.state.resources.money=5000;const beforeTurn=e.state.turn,r=e.takeIntercityTrip('city.nordhafen');assert.equal(r.ok,true);assert.ok(e.state.turn>=beforeTurn+2);assert.equal(e.state.stats.intercityTrips,1);assert.equal(e.state.externalTravelHistory[0].destinationId,'city.nordhafen');});
test('Fernreise ist außerhalb Bahnhof gesperrt',()=>{const e=engine();assert.equal(e.takeIntercityTrip('city.nordhafen').ok,false);});
test('Migration von LC10 ergänzt neue Felder',()=>{const old=engine().state;delete old.casinoFloor;delete old.trainingHistory;delete old.externalTravelHistory;old.schema=11;old.version='0.16.0-living-city-10';const e=new API.GameEngine({state:old});assert.equal(e.state.schema,12);assert.ok(e.state.casinoFloor);assert.ok(Array.isArray(e.state.trainingHistory));});
test('3500-Zug-Langlauf bleibt stabil',()=>{const e=engine(()=>0.41);for(let i=0;i<3500;i++){e.advanceTurn();if(e.getCrewInitiatives().length)e.resolveCrewInitiative(e.getCrewInitiatives()[0].id,['support','observe','redirect'][i%3]);}assert.equal(e.state.schema,12);assert.ok(Number.isFinite(e.state.resources.money));assert.equal(e.getCityTrends().districts.length,12);});
console.log(`PASS: LIVING-CITY-11 Engine – ${pass}/${pass} Tests erfolgreich.`);
