const fs=require('fs');const path=require('path');const assert=require('assert');const root=path.join(__dirname,'..');const read=(f)=>fs.readFileSync(path.join(root,f),'utf8');
const html=read('index.html'),css=read('lc11-visual-polish-6.css')+read('lc11-visual-polish-6b.css')+read('lc11-visual-polish-6c.css')+read('lc11-visual-polish-6d.css')+read('lc11-visual-polish-6e.css'),closeCss=read('lc11-close-control.css'),ui=read('lc11-ui.js'),data=read('lc11-data.js');
assert.ok(html.includes('lc11-visual-polish-6.css')&&html.includes('lc11-visual-polish-6b.css')&&html.includes('lc11-visual-polish-6c.css')&&html.includes('lc11-close-control.css'));
assert.ok(html.indexOf('lc11-visual-polish-5b.css')<html.indexOf('lc11-visual-polish-6.css'));
assert.ok(html.indexOf('lc11-visual-polish-6.css')<html.indexOf('lc11-visual-polish-6b.css'));
assert.ok(html.indexOf('lc11-visual-polish-6b.css')<html.indexOf('lc11-visual-polish-6c.css'));
assert.ok(html.indexOf('lc11-visual-polish-6c.css')<html.indexOf('lc11-close-control.css'),'Kritischer Close-Control-Layer muss nach Visual Polish VI laden.');
assert.ok(closeCss.includes('@import url("lc11-visual-polish-6d.css");')&&closeCss.includes('@import url("lc11-visual-polish-6e.css");'),'VI-E/F/G/H/I/J/K muss vor dem finalen Close-Control-Regelsatz importiert werden.');
assert.ok(html.includes('0.17.6 LIVING-CITY-11 VISUAL-POLISH-VI'));
assert.ok(data.includes("version:'0.17.6-living-city-11-visual-polish-6'"));
assert.ok(ui.includes('0.17.6 · Schema 12'));
[
  '--vp6-cyan:#79f1ff','body::after','.district-node[data-location="location.casino.9909"]','.district-node[data-location="location.station.ghost"]','.direct-target::before','.lc11-feature.casino::before','.lc11-reels{','.lc11-training-hero::after','.scene-hero::after','.combat-stage{','@keyframes vp6SceneSweep','@media(prefers-reduced-motion:reduce)','body.lc09-reduced-motion','--vp6-text-secondary:#c4d2df','.tab.active{','.btn:focus-visible','@media (min-width:1100px) and (max-height:800px)','Kleine Desktop-Höhen: weniger Leerraum statt kleinere Schrift','Visual-Polish VI-B: Aktionsleiste als klare Entscheidungshierarchie','.action-panel .group-title::after','.action-panel .action-card:focus-visible','.action-panel .cost{','Visual-Polish VI-C: Boss-Zentrale mit klarer Lage-, Warn- und Wertehierarchie','.boss-panel .decision-card::before','.boss-panel .warning:first-child','.boss-panel .detail-box[open]','.boss-panel .location-now{','Visual-Polish VI-D: Stadtkarte mit klarer Besitz-, Gefahren- und Routenhierarchie','.district-node .owner-ring.owner-player','.district-node.pressure-critical .zone','.district-node.event-hot .node-core','.district-node:focus-visible .zone','Visual Polish VI-E · Kartenleseschlüssel','Rein präsentational und geometrieneutral','.legend>span{','.map-commandbar{','.map-callout::before{','content:"LAGE"','.map-direct-targets{','.direct-target:hover:not(:disabled),.direct-target:focus-visible','Kartenhöhe-Vertrag: VI-E verändert bei niedrigen Desktops keinerlei Maße','Visual Polish VI-F · Bezirksmarker als kompakte Lageinstrumente','.district-node .node-label{','.district-node.pressure-critical .node-pressure','.district-node.current .node-label','.district-node .asset-count{','Visual Polish VI-G · Straßen-, Bahn- und Routenhierarchie','.route.reachable{','.train-route.reachable{','.route.planned{','.train-route.planned{','.route.chosen,.train-route.chosen{','@keyframes vp6RouteFlow','@keyframes vp6RailFlow','Visual Polish VI-H · Ereignis- und Gefahrenlagen ohne zusätzliche Kartenebene','@keyframes vp6EventPulse','Visual Polish VI-I · Marker-Priorität und optische Ruhe','.district-node.current:not(.event-hot) .node-core{','.district-node.pressure-critical .asset-pin','Visual Polish VI-J · Kombinationslagen mit eindeutiger Priorität','.district-node.selected .owner-ring.owner-rival{','.district-node.selected.event-hot.pressure-critical .owner-ring.owner-rival{','.district-node.current.selected.event-hot.pressure-critical .node-label{','Visual Polish VI-K · Innenräume mit klarer Tiefen- und Interaktionshierarchie','.scene-depth.back{','.scene-hotspot:hover,.scene-hotspot:focus-within{','.interior-action:hover:not(:disabled),.interior-action:focus-within{','.scene-alert{','.theme-station .scene-sign{'
].forEach((x)=>assert.ok(css.includes(x),x));
assert.ok(css.includes('button:focus-visible')&&css.includes('.district-node:focus-visible'),'Fokuszustände müssen sichtbar bleiben.');
assert.ok(!css.includes('pointer-events:auto'),'Visual Polish VI darf keine eigene aktive Interaktionsebene erzwingen.');
const viE=read('lc11-visual-polish-6d.css')+read('lc11-visual-polish-6e.css');
assert.ok(!/(^|[;{])\s*(padding|min-height|min-width|max-height|max-width|grid-template(?:-areas|-columns|-rows)?)\s*:/m.test(viE),'VI-E/F/G/H/I/J/K darf keine Layoutmaße oder Grid-Geometrie setzen.');
const pointerAuto=(closeCss.match(/pointer-events:auto/g)||[]).length;assert.equal(pointerAuto,1,'Nur Close-Control darf pointer-events:auto explizit setzen.');
assert.ok(closeCss.includes('z-index:120!important')&&closeCss.includes('visibility:visible!important'));
console.log('PASS: Visual-Polish VI – räumliche Kartenbühne, Spezialorte, Aktionsleiste, Boss-Zentrale, Kartenlage, geometrieneutraler Kartenleseschlüssel, Bezirksmarker, Routenhierarchie, vertiefte Innenraumhierarchie, Kampf und Reduced-Motion geprüft.');
