'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');const path=require('node:path');
const root=path.join(__dirname,'..'),repo=path.join(root,'..');
const read=(f)=>fs.readFileSync(f,'utf8');
const repair=read(path.join(root,'repair-04a.js'));
const lc05=read(path.join(root,'lc05-ui.js'));
const revival=read(path.join(root,'revival-ui.js'));
const app=read(path.join(root,'app.js'));
const refresh=read(path.join(root,'ui-refresh.js'));
const lc05b=read(path.join(root,'lc05b-ui.js'));
const html=read(path.join(root,'index.html'));
const launcher=read(path.join(repo,'START_GAME.sh'));
assert.ok(!repair.includes('MutationObserver'),'04A darf keinen globalen MutationObserver mehr besitzen.');
assert.ok(!lc05.includes('MutationObserver'),'LC05 darf keinen globalen MutationObserver mehr besitzen.');
assert.ok(!lc05b.includes('MutationObserver'),'LC05B darf keinen globalen MutationObserver einführen.');
assert.ok(!revival.includes('setTimeout(render,0)'),'Revival darf nicht nach jedem Klick blind vollständig rendern.');
assert.ok(!lc05.includes('setTimeout(render,0)'),'LC05 darf nicht nach jedem Klick blind vollständig rendern.');
assert.ok(refresh.includes('let pending=false')&&refresh.includes('requestAnimationFrame'),'Refresh muss gedrosselt und frame-basiert sein.');
assert.ok(refresh.includes("new Event('revival-render')")&&refresh.includes('LIVING_CITY_04A')&&refresh.includes('LIVING_CITY_05_UI')&&refresh.includes('LIVING_CITY_05B_UI'),'Koordinierte Modulaktualisierung fehlt.');
const order=['revival-ui.js','repair-04a.js','lc05-ui.js','lc05b-ui.js','ui-refresh.js'].map((n)=>html.indexOf(`src="${n}"`));
assert.ok(order.every((v)=>v>=0)&&order.every((v,i)=>i===0||v>order[i-1]),'Refresh-Scriptreihenfolge ist falsch.');
assert.ok(launcher.indexOf('google-chrome')>=0&&launcher.indexOf('firefox')>=0&&launcher.indexOf('google-chrome')<launcher.indexOf('firefox'),'Linux-Launcher muss Chrome vor Firefox priorisieren.');
console.log('PASS: Chrome-/Performance-Regression – keine DOM-Render-Schleife, gedrosselter Refresh und Chrome-first geprüft.');
