'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.join(__dirname,'..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const css=fs.readFileSync(path.join(root,'revival.css'),'utf8');
const ui=fs.readFileSync(path.join(root,'revival-ui.js'),'utf8');
const DATA=require('../revival-data.js');
const {GameEngine}=require('../revival-engine.js');
const order=['data.js','revival-data.js','engine.js','revival-missions.js','revival-world.js','revival-engine.js','app.js','revival-ui.js'].map((name)=>html.indexOf(`src="${name}"`));
assert.ok(order.every((n)=>n>=0),'Revival-Scripts fehlen im HTML.');
for(let i=1;i<order.length;i+=1)assert.ok(order[i]>order[i-1],`Script-Reihenfolge fehlerhaft bei ${i}.`);
assert.ok(html.includes('revival.css'),'Revival-CSS fehlt.');
assert.equal(DATA.schema,5);assert.equal(DATA.version,'0.10.0-living-city-04');assert.equal(DATA.missionTemplates.length,8);assert.equal(DATA.cityEvents.length,7);assert.equal(DATA.milestones.length,5);
['getDirectorSummary','acceptMission','spawnCityEvent','getRivalRelationsOverview','getCityPhase'].forEach((name)=>assert.equal(typeof GameEngine.prototype[name],'function',`Engine-Methode ${name} fehlt.`));
['director-strip','mission-card','event-halo','prestige-medal'].forEach((selector)=>assert.ok(css.includes(`.${selector}`),`CSS-Komponente ${selector} fehlt.`));
assert.ok(ui.includes('data-revival-accept')&&ui.includes('revivalDirectorPanel'),'Director-UI-Vertrag unvollständig.');
assert.equal((css.match(/\{/g)||[]).length,(css.match(/\}/g)||[]).length,'Revival-CSS-Klammern unausgeglichen.');
console.log('PASS: Revival-Vertrag – Modulreihenfolge, Daten, Engine und Visual Layer geprüft.');
