'use strict';
const assert=require('node:assert/strict');
const {GameEngine,seededRandom}=require('../revival-engine.js');
const tests=[];
const test=(name,fn)=>tests.push({name,fn});
const engineWith=(random=()=>.99)=>new GameEngine({random});
const go=(engine,id)=>{engine.state.currentLocationId=id;engine.state.selectedLocationId=id;};

test('Revival startet mit Schema 5 und vier Auftragsangeboten',()=>{const e=engineWith(seededRandom(1));assert.equal(e.state.schema,5);assert.equal(e.state.version,'0.10.1-living-city-04a');assert.equal(e.state.missions.offers.length,4);});
test('Dynamischer Auftrag kann angenommen werden',()=>{const e=engineWith(seededRandom(45)),offer=e.state.missions.offers[0],r=e.acceptMission(offer.id);assert.equal(r.ok,true);assert.equal(e.state.missions.active.length,1);assert.ok(e.state.missions.active[0].deadline>e.state.turn);});
test('Gebietsauftrag wird abgeschlossen, belohnt und verkettet',()=>{const e=engineWith(()=>.5),t=e.data.missionTemplates.find((m)=>m.id==='mission.territory.push'),m=e.createMissionFromTemplate(t);e.state.missions.offers=[m];e.state.missions.active=[];e.acceptMission(m.id);const before=e.state.resources.money,target=e.data.world.locations.find((l)=>e.getDistrict(l.id).owner!=='player'),d=e.getDistrict(target.id);d.owner='player';d.control=80;d.rival=20;e.resolveMissions();assert.equal(e.state.stats.missionsCompleted,1);assert.ok(e.state.resources.money>before);assert.ok(e.state.missions.offers.some((x)=>x.templateId==='mission.rival.break'));});
test('Abgelaufener Auftrag wird als Fehlschlag archiviert',()=>{const e=engineWith(()=>.5),t=e.data.missionTemplates.find((m)=>m.id==='mission.travel.web'),m=e.createMissionFromTemplate(t);e.state.missions.offers=[m];e.state.missions.active=[];e.acceptMission(m.id);e.state.turn=e.state.missions.active[0].deadline+1;e.resolveMissions();assert.equal(e.state.stats.missionsFailed,1);assert.equal(e.state.missions.failed[0].status,'failed');});
test('Stadtereignis verändert Bezirk und erscheint im Director',()=>{const e=engineWith(()=>.5),before=e.getDistrict('location.oldtown.central').police,event=e.spawnCityEvent(true,'event.police.sweep','location.oldtown.central');assert.ok(event);assert.ok(e.getDistrict('location.oldtown.central').police>before);assert.ok(e.getDirectorSummary().events.some((x)=>x.locationId==='location.oldtown.central'));});
test('Maximal zwei Stadtereignisse bleiben gleichzeitig aktiv',()=>{const e=engineWith(()=>.5);assert.ok(e.spawnCityEvent(true,'event.market.boom','location.market.black'));assert.ok(e.spawnCityEvent(true,'event.blackout','location.blocks.east'));assert.equal(e.spawnCityEvent(true,'event.neon.festival','location.neon.cellar_club'),null);assert.equal(e.state.cityEvents.length,2);});
test('Bahnstreik erhöht nur Fernlinienkosten',()=>{const e=engineWith(()=>.5);go(e,'location.station.ghost');const options=e.getTravelOptions(),train=options.find((o)=>o.mode==='train'),road=options.find((o)=>o.mode!=='train'),roadBefore=road?.cost;e.spawnCityEvent(true,'event.transit.strike','location.station.ghost');const next=e.getTravelOptions();assert.equal(next.find((o)=>o.mode==='train'&&o.to===train.to).cost,train.cost+25);if(road)assert.equal(next.find((o)=>o.mode===road.mode&&o.to===road.to).cost,roadBefore);});
test('Rivalenbeziehungen sind begrenzt und verständlich',()=>{const e=engineWith(),a='rival.red_knives',b='rival.grey_union';assert.equal(e.adjustRivalRelation(a,b,-500),-100);assert.equal(e.getRivalRelationLabel(e.getRivalRelation(a,b)),'Offener Krieg');assert.equal(e.adjustRivalRelation(a,b,500),100);assert.equal(e.getRivalRelationLabel(e.getRivalRelation(a,b)),'Pakt');});
test('Offener Rivalenkrieg wird als KI-Ziel erkannt',()=>{const e=engineWith(),a='rival.red_knives',b='rival.neon_ghosts';e.adjustRivalRelation(a,b,-100);assert.equal(e.getRivalWarTarget(a),b);});
test('Director berechnet Spannung, Chancen und Prestige',()=>{const d=engineWith().getDirectorSummary();assert.ok(d.tension>=0&&d.tension<=100);assert.ok(d.opportunity>=0&&d.opportunity<=100);assert.ok(Number.isFinite(d.prestige));assert.ok(d.phase.label);});
test('Stadtphase wechselt deterministisch',()=>{const e=engineWith(),first=e.getCityPhase().key;e.state.turn+=1;assert.notEqual(first,e.getCityPhase().key);});
test('Meilenstein wird genau einmal belohnt',()=>{const e=engineWith(),before=e.state.resources.money;e.data.world.locations.slice(0,3).forEach((l)=>{e.getDistrict(l.id).owner='player';});e.evaluateMilestones();assert.ok(e.state.milestones.includes('milestone.first_ring'));const after=e.state.resources.money;e.evaluateMilestones();assert.equal(e.state.resources.money,after);assert.ok(after>before);});
test('Schema-4-Spielstand wird um Revival-Zustand ergänzt',()=>{const old={schema:4,version:'0.9.0-living-city-03',turn:20,currentLocationId:'location.bunker.main',selectedLocationId:'location.bunker.main',resources:{money:900,supplies:5},boss:{respect:55,fear:30,loyalty:65,influence:50,heat:20,notoriety:38},districts:{},gang:[],assets:[],history:[]};const e=new GameEngine({state:old,random:()=>.5});assert.equal(e.state.schema,5);assert.ok(e.state.missions);assert.ok(e.state.director);assert.equal(Object.keys(e.state.rivalRelations).length,3);});
test('Missionfortschritt bleibt zwischen 0 und 100 Prozent',()=>{const e=engineWith(),m=e.state.missions.offers[0],p=e.getMissionProgress(m);assert.ok(p.pct>=0&&p.pct<=100);});
test('Director bleibt über 250 Züge numerisch stabil',()=>{const e=engineWith(seededRandom(101010));e.state.resources.money=250000;e.state.resources.supplies=20000;e.state.bank.balance=100000;for(let i=0;i<250;i+=1){e.advanceTurn();const d=e.getDirectorSummary();assert.ok(Number.isFinite(d.tension));assert.ok(Number.isFinite(d.opportunity));assert.ok(Number.isFinite(d.prestige));assert.ok(e.state.cityEvents.length<=2);}});

let passed=0;for(const {name,fn} of tests){try{fn();passed+=1;}catch(error){console.error(`FAIL: ${name}`);throw error;}}
console.log(`PASS: Revival-Engine – ${passed}/${tests.length} Tests erfolgreich.`);
