'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { GameEngine } = require('../engine.js');
const root = path.join(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const app = fs.readFileSync(path.join(root, 'app.js'), 'utf8');
const css = fs.readFileSync(path.join(root, 'styles.css'), 'utf8');
const ids = [...html.matchAll(/id="([^"]+)"/g)].map((m) => m[1]);
assert.equal(new Set(ids).size, ids.length, 'Doppelte statische HTML-ID gefunden.');
const directRefs = new Set([...app.matchAll(/\$\('#([^']+)'\)/g)].map((m) => m[1]));
const declared = new Set([...(`${html}\n${app}`).matchAll(/id=["']([^"']+)["']/g)].map((m) => m[1]));
const missing = [...directRefs].filter((id) => !declared.has(id));
assert.deepEqual(missing, [], `Fehlende DOM-IDs: ${missing.join(', ')}`);
const engineCalls = new Set([...app.matchAll(/engine\.([A-Za-z0-9_]+)\s*\(/g)].map((m) => m[1]));
const proto = GameEngine.prototype;
const missingMethods = [...engineCalls].filter((name) => typeof proto[name] !== 'function' && !['state'].includes(name));
assert.deepEqual(missingMethods, [], `App ruft unbekannte Engine-Methoden: ${missingMethods.join(', ')}`);
assert.ok(html.indexOf('data.js') < html.indexOf('engine.js') && html.indexOf('engine.js') < html.indexOf('app.js'), 'Script-Reihenfolge falsch.');
assert.equal((css.match(/\{/g)||[]).length, (css.match(/\}/g)||[]).length, 'CSS-Klammern unausgeglichen.');
assert.ok(html.includes('personDialog') && html.includes('combatDialog') && html.includes('casinoPanel') && html.includes('bankPanel'), 'Kernpanels fehlen.');
console.log(`PASS: Static-UI – ${ids.length} IDs, ${directRefs.size} Direktreferenzen, ${engineCalls.size} Engine-Aufrufe geprüft.`);
