'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.join(__dirname,'..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const app=fs.readFileSync(path.join(root,'repair-bootstrap.js'),'utf8')+'\n'+fs.readFileSync(path.join(root,'repair-04a.js'),'utf8');
const css=fs.readFileSync(path.join(root,'repair-04a.css'),'utf8');
const {GameEngine}=require('../revival-engine.js');
const DATA=require('../revival-data.js');
const seeded=(seed=7)=>()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};
assert.ok(html.includes('id="endTurnButton"'),'Zug-beenden-Button fehlt.');
assert.ok(html.includes('data-tab="rivals"')&&html.includes('id="rivalsPanel"'),'Rivalen-Hauptbereich fehlt.');
['mapZoomIn','mapZoomOut','mapZoomReset','mapQuickbar'].forEach((id)=>assert.ok(html.includes(`id="${id}"`),`Kartenbedienung ${id} fehlt.`));
assert.ok(app.includes("pppoppi-bunkerwahrheit-html-v0100"),'Neuer Speicherkey fehlt.');
assert.ok(app.includes("pppoppi-bunkerwahrheit-html-v090"),'Migration vom 0.9-Speicherkey fehlt.');
assert.ok(html.includes('repair-bootstrap.js')&&html.includes('repair-04a.js')&&html.includes('repair-04a.css'),'04A-Reparaturschicht nicht eingebunden.');
['.route.reachable','.route.chosen','.map-quickbar','.control-ring','.rival-card'].forEach((selector)=>assert.ok(css.includes(selector),`Karten-/Rivalenstil ${selector} fehlt.`));
const e=new GameEngine({random:seeded(4),data:DATA});
e.assignCrewTask(e.state.gang[0].id,'task.rest');
const before=e.state.turn,cycles=e.state.stats.autonomousCycles;
const result=e.endTurn();
assert.equal(result.ok,true);assert.equal(e.state.turn,before+1);assert.ok(e.state.stats.autonomousCycles>cycles,'Autonome Systeme liefen beim Zugende nicht.');
e.state.combatSession={id:'test'};const blocked=e.endTurn();assert.equal(blocked.ok,false);assert.match(blocked.reason,/Kampf/i);e.state.combatSession=null;
e.state.casino.poker={status:'playing'};const pokerBlocked=e.endTurn();assert.equal(pokerBlocked.ok,false);assert.match(pokerBlocked.reason,/Poker/i);
console.log('PASS: UI-Regression – Zugsteuerung, Rivalen, Karte, Speicher-Migration und Sperrlogik geprüft.');
