(function () {
  'use strict';
  const STORAGE_KEY='pppoppi-bunkerwahrheit-html-v090';
  const LEGACY_KEYS=['pppoppi-bunkerwahrheit-html-v080','pppoppi-bunkerwahrheit-html-v070','pppoppi-bunkerwahrheit-html-v060'];
  const DATA=window.GAME_DATA;
  const {GameEngine,SKILL_LABELS}=window.GAME_ENGINE;
  const $=(s)=>document.querySelector(s), $$=(s)=>Array.from(document.querySelectorAll(s));
  const esc=(v)=>String(v??'').replace(/[&<>'"]/g,(m)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
  const money=(v)=>`${Number(v||0).toLocaleString('de-DE',{maximumFractionDigits:2})} €`;
  const initials=(name)=>String(name).replace(/[„“"']/g,'').split(/\s+/).slice(0,2).map((p)=>p[0]).join('').toUpperCase();
  let engine=new GameEngine({state:loadState()||undefined});
  let combatSelection=new Set();
  let activePersonId=null;

  function loadState(){
    for(const key of [STORAGE_KEY,...LEGACY_KEYS]){
      try{const raw=localStorage.getItem(key);if(raw)return JSON.parse(raw);}catch(error){console.warn('Speicherstand konnte nicht gelesen werden.',error);}
    }
    return null;
  }
  function saveState(manual=false){
    try{localStorage.setItem(STORAGE_KEY,engine.exportState());$('#saveStatus').textContent=manual?'Spielstand gespeichert':'Automatisch lokal gespeichert';if(manual)setTimeout(()=>$('#saveStatus').textContent='Automatisch lokal gespeichert',1400);}catch(error){$('#saveStatus').textContent='Speichern nicht möglich';console.warn(error);}
  }
  function notify(text){$('#tickerText').textContent=text;}
  function mutate(result,successText){if(!result?.ok){notify(result?.reason||'Aktion nicht möglich.');return false;}if(successText)notify(successText);renderAll();saveState();return true;}

  function renderAll(){renderTop();renderBoss();renderMap();renderDistrict();renderCrew();renderAssets();renderBank();renderNetwork();renderCasino();renderLog();saveState();if($('#personDialog').open&&activePersonId)renderPersonDialog(activePersonId);if($('#combatDialog').open)renderCombatDialog();}

  function renderTop(){
    const s=engine.state,portfolio=engine.getPortfolioSummary(),invest=engine.getInvestmentPortfolio();
    const items=[['Zug',s.turn],['Bargeld',money(s.resources.money)],['Bank',money(s.bank.balance)],['Vorrat',s.resources.supplies],['Crew',s.gang.length],['Cashflow',`${portfolio.net>=0?'+':''}${money(portfolio.net)}`],['Anlagen',money(invest.value)]];
    $('#topKpis').innerHTML=items.map(([l,v])=>`<div class="kpi"><span>${esc(l)}</span><strong>${esc(v)}</strong></div>`).join('');
  }

  function renderBoss(){
    const s=engine.state,d=engine.getDecisionSupport(),profile=engine.getBossProfile(),city=engine.getCitySummary();
    $('#bossTitle').textContent=profile.title;$('#bossRank').textContent=d.rank;$('#bossNote').textContent=profile.note;$('#currentLocation').textContent=engine.getCurrentLocation().title;
    const decisions=[['Vermögen',money(d.netWorth)],['Cashflow/Zug',money(d.cashflow)],['Anlagewert',money(d.investmentValue)],['Razzia',`${d.raidRisk}%`],['Beitritt',`${d.recruitChance}%`],['Freie Crew',`${d.readyCrew}/${d.totalCrew}`],['Crewtreue',`${d.avgLoyalty}%`],['Gebiete',`${city.controlled}/${city.total}`]];
    $('#decisionGrid').innerHTML=decisions.map(([l,v])=>`<div class="decision-card"><span>${esc(l)}</span><strong>${esc(v)}</strong></div>`).join('');
    $('#bossWarnings').innerHTML=d.warnings.map((w)=>`<div class="warning">${esc(w)}</div>`).join('');
    $('#bossSkills').innerHTML=Object.entries(s.boss.skills).map(([k,v])=>skillBar(SKILL_LABELS[k]||k,v,s.boss.skillXp[k]||0)).join('');
    const metricLabels={respect:'Respekt',fear:'Furcht',loyalty:'Loyalität',influence:'Einfluss',heat:'Fahndung',notoriety:'Bekanntheit'};
    $('#bossMetrics').innerHTML=Object.entries(metricLabels).map(([k,l])=>`<div class="metric-row"><span>${l}</span><b>${s.boss[k]}</b><div class="bar"><i style="width:${s.boss[k]}%"></i></div></div>`).join('');
    $('#citySummary').innerHTML=`<div><span>Ø Kontrolle</span><strong>${city.avgControl}%</strong></div><div><span>Ø Rivalen</span><strong>${city.avgRival}%</strong></div><div><span>Gangstärke</span><strong>${engine.getGangPower()}</strong></div><div><span>Maulwürfe</span><strong>${s.moles.length}</strong></div>`;
  }
  function skillBar(label,level,xp){const pct=Math.min(100,Math.round(xp/engine.skillThreshold(level)*100));return`<div class="skill"><span>${esc(label)}</span><b>${level}/10</b><div class="bar"><i style="width:${pct}%"></i></div></div>`;}

  function hexPoints(cx,cy,r){return Array.from({length:6},(_,i)=>{const a=Math.PI/3*i+Math.PI/6;return`${(cx+Math.cos(a)*r).toFixed(1)},${(cy+Math.sin(a)*r).toFixed(1)}`;}).join(' ');}
  function ownerClass(owner){return owner==='player'?'owner-player':owner==='neutral'?'owner-neutral':'owner-rival';}
  function renderMap(){
    const selected=engine.state.selectedLocationId,current=engine.state.currentLocationId,map=Object.fromEntries(DATA.world.locations.map((l)=>[l.id,l]));
    const routes=DATA.world.connections.map(([a,b])=>{const p1=map[a],p2=map[b],active=a===current||b===current;return`<line class="route ${active?'current':''}" x1="${p1.x}" y1="${p1.y}" x2="${p2.x}" y2="${p2.y}"></line>`;}).join('');
    const trains=DATA.world.trainRoutes.map((r)=>{const p1=map[r.from],p2=map[r.to];return`<line class="train-route" x1="${p1.x}" y1="${p1.y}" x2="${p2.x}" y2="${p2.y}"></line>`;}).join('');
    const nodes=DATA.world.locations.map((l)=>{const d=engine.getDistrict(l.id),assets=engine.state.assets.filter((a)=>a.locationId===l.id).length,r= l.id===selected?54:48;return`<g class="district-node ${l.id===selected?'selected':''} ${l.id===current?'current':''}" data-location="${l.id}" tabindex="0" role="button" aria-label="${esc(l.title)}"><polygon class="zone" points="${hexPoints(l.x,l.y,r+10)}"></polygon><circle class="owner-ring ${ownerClass(d.owner)}" cx="${l.x}" cy="${l.y}" r="34"></circle><circle class="node-core" cx="${l.x}" cy="${l.y}" r="27"></circle><text class="node-control" x="${l.x}" y="${l.y+5}" text-anchor="middle">${d.control}</text><text class="node-label" x="${l.x}" y="${l.y+58}" text-anchor="middle">${esc(l.short)}</text><text class="node-sub" x="${l.x}" y="${l.y+72}" text-anchor="middle">${esc(engine.ownerLabel(d.owner))}</text>${assets?`<circle class="asset-pin" cx="${l.x-30}" cy="${l.y-31}" r="6"></circle>`:''}${d.intel?`<circle class="intel-pin" cx="${l.x+30}" cy="${l.y-31}" r="${4+d.intel}"></circle>`:''}${l.kind==='station'?`<rect class="train-pin" x="${l.x-5}" y="${l.y+28}" width="10" height="10" rx="2"></rect>`:''}</g>`;}).join('');
    $('#cityMap').innerHTML=`<defs><pattern id="grid" width="40" height="40" patternUnits="userSpaceOnUse"><path d="M 40 0 L 0 0 0 40" class="grid-line" fill="none"></path></pattern></defs><rect class="map-bg" width="1000" height="700"></rect><rect width="1000" height="700" fill="url(#grid)"></rect>${routes}${trains}${nodes}`;
    const l=engine.getLocation(),d=engine.getDistrict();$('#mapCallout').innerHTML=`<strong>${esc(l.title)} · ${esc(engine.ownerLabel(d.owner))}</strong><span>${d.control}% Kontrolle · ${d.rival}% Rivalen · ${d.police}% Polizei · Aufklärung ${d.intel}/5</span>`;
  }

  function statBar(label,value,color=''){return`<div class="stat-bar"><span><i>${esc(label)}</i><b>${value}%</b></span><div class="bar"><i style="width:${value}%;${color?`background:${color}`:''}"></i></div></div>`;}
  function costText(cost={}){const p=[];if(cost.money)p.push(money(cost.money));if(cost.supplies)p.push(`${cost.supplies} Vorrat`);return p.join(' · ')||'kein Einsatz';}
  function renderDistrict(){
    const l=engine.getLocation(),d=engine.getDistrict(),isHere=l.id===engine.state.currentLocationId;
    const actionsBy={business:[],influence:[],conflict:[]};DATA.actions.forEach((a)=>actionsBy[a.category].push(a));
    const actionHtml=Object.entries(actionsBy).map(([cat,items])=>`<div><div class="group-title">${cat==='business'?'Geschäft':cat==='influence'?'Einfluss':'Konflikt'}</div><div class="action-grid">${items.map((a)=>{const av=engine.getActionAvailability(a);return`<button class="action-card tone-${a.tone}" data-game-action="${a.id}" ${av.ok?'':`disabled title="${esc(av.reason)}"`}><span class="action-icon">${esc(a.icon)}</span><span class="action-copy"><strong>${esc(a.title)}</strong><small>${esc(a.description)}</small></span><span class="cost">${esc(costText(a.cost))}</span></button>`;}).join('')}</div></div>`).join('');
    const offers=engine.getAvailableProperties(l.id);
    const travelOptions=engine.getTravelOptions();
    const toSelected=travelOptions.filter((o)=>o.to===l.id);
    let travelHtml='';
    if(!isHere){travelHtml=toSelected.length?`<div class="subsection"><div class="group-title">ANREISE</div>${toSelected.map((o)=>`<button class="travel-card" data-travel-to="${o.to}" data-travel-mode="${o.mode}"><b>${esc(o.title)}</b><small>${money(o.cost)} · ${o.mode==='train'?'Bahn':'Straße'}</small></button>`).join('')}</div>`:`<div class="warning">Von ${esc(engine.getCurrentLocation().title)} gibt es keine direkte Verbindung. Reise etappenweise über die Karte.</div>`;}
    else if(l.kind==='station'){travelHtml=`<div class="subsection"><div class="group-title">BAHNHOF · FERNLINIEN</div><div class="card-grid">${travelOptions.filter((o)=>o.mode==='train').map((o)=>`<button class="travel-card" data-travel-to="${o.to}" data-travel-mode="train"><b>${esc(o.title)}</b><small>${money(o.cost)}</small></button>`).join('')}</div></div>`;}
    let special='';
    if(isHere&&l.kind==='market') special=renderGearShop();
    if(isHere&&l.kind==='residential') special=renderMartialArtsQuick();
    if(isHere&&l.kind==='casino') special=`<div class="subsection"><div class="group-title">CASINO 9909</div><button class="mini-btn good" data-open-tab="casino">Poker & Spielautomaten öffnen</button></div>`;
    $('#districtPanel').innerHTML=`<div class="district-head"><div><span class="eyebrow">${isHere?'DU BIST HIER':'AUSGEWÄHLTER BEZIRK'}</span><h3>${esc(l.title)}</h3></div><span class="status-pill ${d.owner==='player'?'':d.owner==='neutral'?'cyan':'red'}">${esc(engine.ownerLabel(d.owner))}</span></div><p class="district-description">${esc(l.description)}</p><div class="district-bars">${statBar('Kontrolle',d.control)}${statBar('Rivalen',d.rival,'var(--red)')}${statBar('Polizei',d.police,'var(--cyan)')}${statBar('Unruhe',d.unrest,'var(--gold)')}</div>${travelHtml}<div class="action-groups">${actionHtml}</div><div class="subsection"><div class="section-head"><div><span class="eyebrow">IMMOBILIEN</span><h3>Lokale Kaufangebote</h3></div><span class="status-pill">${offers.length}</span></div><div class="card-grid">${offers.length?offers.map((p)=>`<div class="info-card"><div class="row-between"><div><b>${esc(p.icon)} · ${esc(p.title)}</b><p class="muted">${esc(p.description)}</p></div><span class="status-pill">${money(p.cost)}</span></div><div class="card-meta"><span class="tag">Netto ca. ${money(p.projectedNet)}/Z</span></div><button class="mini-btn good" data-buy-property="${p.id}" ${isHere?'':'disabled'}>Kaufen</button></div>`).join(''):'<p class="muted">Keine neuen Objekte in diesem Bezirk.</p>'}</div></div>${special}`;
  }

  function renderGearShop(){return`<div class="subsection"><div class="section-head"><div><span class="eyebrow">EISENLADEN</span><h3>Schutz- & Taktikausrüstung</h3></div></div><p class="muted">Reine Spielwerte: Schutz, Koordination und Kampfbonus.</p><div class="card-grid">${DATA.gear.map((g)=>`<div class="info-card"><div class="row-between"><b>${esc(g.title)}</b><span class="status-pill">${money(g.cost)}</span></div><p class="muted">${esc(g.description)}</p><div class="card-meta"><span class="tag">Kampf +${g.combatBonus||0}</span><span class="tag">Schutz +${g.defenseBonus||0}</span><span class="tag">Analyse +${g.analysisBonus||0}</span></div><button class="mini-btn good" data-buy-gear="${g.id}">Kaufen</button></div>`).join('')}</div></div>`;}
  function renderMartialArtsQuick(){return`<div class="subsection"><div class="section-head"><div><span class="eyebrow">DOJO 9909</span><h3>Kampfsport lernen</h3></div></div><p class="muted">Crewmitglied im Detail öffnen, um eine Kampfsportart dauerhaft zu trainieren.</p></div>`;}

  function renderCrew(){
    $('#crewPanel').innerHTML=`<div class="section-head"><div><span class="eyebrow">PERSONEN</span><h3>${engine.state.gang.length} Crewmitglieder</h3></div><span class="status-pill">${engine.getFreeCrew().length} frei</span></div><p class="muted">Karten öffnen: Skills, Ausrüstung, Kampfsport, Karriere und autonome Daueraufträge.</p><div class="card-grid">${engine.state.gang.map((m)=>{const st=engine.getMemberStatus(m);const best=Object.entries(m.skills).sort((a,b)=>b[1]-a[1]).slice(0,2);return`<article class="person-card" data-member="${m.id}"><div class="avatar">${esc(initials(m.name))}</div><div><strong>${esc(m.name)}</strong><small>${esc(m.role)} · ${esc(m.trait)} · ${m.age} J.</small><small>${esc(st.label)}</small><div class="card-meta">${best.map(([k,v])=>`<span class="tag">${esc(SKILL_LABELS[k])} ${v}</span>`).join('')}</div></div><div class="person-mini"><span>Macht <b>${m.power}</b></span><span>Treue <b>${m.loyalty}</b></span><span>Siege <b>${m.wins}</b></span></div></article>`;}).join('')}</div>`;
  }

  function renderAssets(){
    const p=engine.getPortfolioSummary();
    $('#assetsPanel').innerHTML=`<div class="section-head"><div><span class="eyebrow">BESITZ</span><h3>${p.count} Betriebe</h3></div><span class="status-pill">${p.net>=0?'+':''}${money(p.net)}/Z</span></div><div class="summary-grid"><div><span>Investiert</span><strong>${money(p.value)}</strong></div><div><span>Brutto</span><strong>${money(p.gross)}</strong></div><div><span>Unterhalt</span><strong>${money(p.upkeep)}</strong></div><div><span>Hotels</span><strong>${p.hotels}</strong></div></div><div class="card-grid" style="margin-top:10px">${engine.state.assets.length?engine.state.assets.map((a)=>assetCard(a)).join(''):'<p class="muted">Noch kein Besitz. Kaufangebote stehen im jeweiligen Bezirk.</p>'}</div>`;
  }
  function assetCard(a){const def=engine.getAssetDefinition(a.propertyId),proj=engine.getAssetProjection(a),crew=(a.assignedCrewIds||[]).map((id)=>engine.getMember(id)?.name).filter(Boolean),available=engine.state.gang.filter((m)=>!(a.assignedCrewIds||[]).includes(m.id)&&(!m.injuredUntil||m.injuredUntil<=engine.state.turn)&&!engine.state.moles.some((x)=>x.memberId===m.id));return`<article class="asset-card"><div class="row-between"><div><h4>${esc(def?.icon||'□')} · ${esc(def?.title||'Betrieb')}</h4><span class="muted">${esc(engine.getLocation(a.locationId).title)} · Stufe ${a.level}</span></div><span class="status-pill">${proj.net>=0?'+':''}${money(proj.net)}/Z</span></div><div class="card-meta"><span class="tag">Investiert ${money(a.invested)}</span><span class="tag">Sicherheit ${proj.security}</span><span class="tag">Crew ${crew.length}/2</span></div><p class="muted">${crew.length?`Zugewiesen: ${esc(crew.join(', '))}`:'Keine feste Crew zugewiesen.'}</p>${crew.length<2&&available.length?`<div class="input-line"><select class="select" id="assetcrew-${a.id}">${available.map((m)=>`<option value="${m.id}">${esc(m.name)} · Geschäft ${m.skills.business}</option>`).join('')}</select><button class="mini-btn" data-assign-asset-crew="${a.id}">Crew zuweisen</button></div>`:''}<div class="button-row"><button class="mini-btn good" data-upgrade-asset="${a.id}">Ausbauen</button><button class="mini-btn danger" data-sell-asset="${a.id}">Verkaufen</button></div></article>`;}

  function renderBank(){
    const invest=engine.getInvestmentPortfolio();
    $('#bankPanel').innerHTML=`<div class="section-head"><div><span class="eyebrow">BANK & BETEILIGUNGEN</span><h3>Lokaler Unternehmensmarkt</h3></div><span class="status-pill">${money(engine.state.bank.balance)}</span></div><div class="bank-actions"><div class="input-line"><input id="bankDepositAmount" type="number" min="1" step="50" value="200"><button class="mini-btn good" data-bank-deposit>Einzahlen</button></div><div class="input-line"><input id="bankWithdrawAmount" type="number" min="1" step="50" value="200"><button class="mini-btn" data-bank-withdraw>Auszahlen</button></div></div><div class="summary-grid"><div><span>Depotwert</span><strong>${money(invest.value)}</strong></div><div><span>Gewinn/Verlust</span><strong>${invest.gain>=0?'+':''}${money(invest.gain)}</strong></div><div><span>Dividenden gesamt</span><strong>${money(engine.state.bank.totalDividends)}</strong></div><div><span>Bankzins</span><strong>${money(engine.state.bank.totalInterest)}</strong></div></div><p class="muted">Kurse werden pro Zug aus Bezirkskontrolle, Unruhe, lokalen Betrieben, Rivalenbesitz, Umsatzentwicklung und Marktimpuls berechnet.</p><div class="card-grid">${DATA.companies.map((def)=>companyCard(def)).join('')}</div>`;
  }
  function companyCard(def){const c=engine.state.market.companies[def.id],h=engine.state.bank.holdings[def.id],delta=c.price-c.lastPrice,history=c.history||[];const min=Math.min(...history),max=Math.max(...history),span=Math.max(.01,max-min);return`<article class="company-card"><div class="company-row"><div><h4>${esc(def.symbol)} · ${esc(def.name)}</h4><span class="muted">${esc(def.sector)} · ${esc(engine.getLocation(def.locationId).title)}</span></div><div class="price ${delta>=0?'up':'down'}">${money(c.price)}</div></div><div class="spark">${history.slice(-18).map((v)=>`<i style="height:${6+((v-min)/span)*18}px"></i>`).join('')}</div><div class="card-meta"><span class="tag">Entwicklung ${c.development}%</span><span class="tag">Umsatz ${money(c.revenue)}</span><span class="tag">Gewinn ${money(c.profit)}</span><span class="tag">Dividende ${(def.dividendRate*100).toFixed(1)}%</span><span class="tag">Besitz ${h?.shares||0} Anteile</span></div><div class="button-row"><button class="mini-btn good" data-buy-shares="${def.id}" data-shares="1">+1</button><button class="mini-btn good" data-buy-shares="${def.id}" data-shares="5">+5</button><button class="mini-btn" data-sell-shares="${def.id}" data-shares="1">-1</button></div></article>`;}

  function renderNetwork(){
    const free=engine.getFreeCrew();
    const institutions=DATA.institutions.map((inst)=>{const mole=engine.state.moles.find((m)=>m.institutionId===inst.id);return`<article class="network-card ${mole?'active':''}"><div class="row-between"><div><h4>${esc(inst.icon)} · ${esc(inst.title)}</h4><p class="muted">${esc(inst.benefit)}</p></div>${mole?`<span class="status-pill">Stufe ${mole.level}</span>`:`<span class="status-pill red">Risiko ${inst.difficulty}</span>`}</div>${mole?`<p class="muted">Maulwurf: ${esc(engine.getMember(mole.memberId)?.name||'?')} · Tarnung ${mole.cover}%</p><button class="mini-btn danger" data-remove-mole="${mole.id}">Abziehen</button>`:`<div class="input-line"><select class="select" id="mole-${inst.id}">${free.map((m)=>`<option value="${m.id}">${esc(m.name)} · Tarnung ${m.skills.stealth} · Analyse ${m.skills.analysis}</option>`).join('')}</select><button class="mini-btn good" data-plant-mole="${inst.id}" ${free.length?'':'disabled'}>Maulwurf setzen</button></div>`}</article>`;}).join('');
    const street=DATA.streetOperations.map((op)=>{const active=engine.state.streetOperations.filter((x)=>x.active&&x.operationId===op.id);return`<article class="network-card"><div class="row-between"><div><h4>${esc(op.title)}</h4><p class="muted">${esc(op.description)}</p></div><span class="status-pill">${money(op.cost)}</span></div><div class="card-meta"><span class="tag">Fahndung +${op.heat}</span><span class="tag">Risiko ${Math.round(op.risk*100)}%</span>${op.income?`<span class="tag">Basis ${money(op.income)}/Z</span>`:''}</div>${op.kind==='recurring'?`<button class="mini-btn good" data-start-street="${op.id}">Im aktuellen Bezirk starten</button><span class="muted"> Aktiv: ${active.length}</span>`:`<div class="input-line"><select class="select" id="contractRival">${engine.getRivalOverview().map((r)=>`<option value="${r.id}">${esc(r.name)} · Macht ${r.power}</option>`).join('')}</select><button class="mini-btn danger" data-start-contract="${op.id}">Fiktiven Auftrag erteilen</button></div>`}</article>`;}).join('');
    $('#networkPanel').innerHTML=`<div class="section-head"><div><span class="eyebrow">MAULWURFNETZ</span><h3>${engine.state.moles.length} aktive Positionen</h3></div></div><p class="muted">Institutionen wirken nur als abstrakte Spielsysteme mit Risiko-/Bonuswerten.</p><div class="card-grid">${institutions}</div><div class="subsection"><div class="section-head"><div><span class="eyebrow">STADT-OPERATIONEN</span><h3>Wiederkehrend & Auftragsjobs</h3></div></div><div class="card-grid">${street}</div></div>`;
  }

  function renderCasino(){
    const here=engine.getCurrentLocation().kind==='casino'; const p=engine.state.casino.poker;
    if(!here){$('#casinoPanel').innerHTML=`<div class="section-head"><div><span class="eyebrow">CASINO 9909</span><h3>Nicht am Spielort</h3></div></div><p class="muted">Reise zum Casino 9909. Vom Geisterbahnhof fährt zusätzlich die Nachtlinie 9.</p>`;return;}
    const slots=DATA.casino.slotMachines.map((m)=>{const last=engine.state.casino.lastSlot?.machineId===m.id?engine.state.casino.lastSlot:null;return`<article class="casino-card"><div class="row-between"><h4>${esc(m.title)}</h4><span class="status-pill">${esc(m.volatility)}</span></div><div class="reels">${(last?.reels||['?','?','?']).map((r)=>`<div class="reel">${esc(r)}</div>`).join('')}</div><div class="input-line"><input id="bet-${m.id}" type="number" min="${m.minBet}" max="${m.maxBet}" value="${m.minBet}"><button class="mini-btn good" data-spin-slot="${m.id}">Drehen</button></div><p class="muted">Einsatz ${m.minBet}–${m.maxBet} €${last?` · Letzte Auszahlung ${money(last.payout)}`:''}</p></article>`;}).join('');
    let poker='';
    if(!p||p.status==='finished'){poker=`<div class="poker-table"><div class="section-head"><div><span class="eyebrow">5-CARD DRAW</span><h3>Poker selbst spielen</h3></div></div>${p?.result?`<p class="muted">Letztes Ergebnis: ${esc(p.result.result)} · ${esc(p.result.playerRank)} gegen ${esc(p.result.dealerRank)} · ${money(p.result.payout)}</p>`:''}<div class="input-line"><input id="pokerBet" type="number" min="10" max="500" value="50"><button class="mini-btn good" data-poker-start>Neue Hand</button></div></div>`;}
    else poker=`<div class="poker-table"><div class="row-between"><div><span class="eyebrow">DEIN BLATT</span><h3>Einsatz ${money(p.bet)}</h3></div><span class="status-pill">Ziehrunden ${p.draws}/2</span></div><p class="muted">Karten anklicken = halten. Nicht gehaltene Karten werden beim Ziehen ersetzt.</p><div class="cards">${p.player.map((c,i)=>`<button class="playing-card ${c.s==='♥'||c.s==='♦'?'red':''} ${p.holds[i]?'held':''}" data-poker-hold="${i}">${esc(c.r)}${esc(c.s)}</button>`).join('')}</div><div class="button-row"><button class="mini-btn" data-poker-draw ${p.draws>=2?'disabled':''}>Karten ziehen</button><button class="mini-btn good" data-poker-finish>Showdown</button></div></div>`;
    $('#casinoPanel').innerHTML=`<div class="section-head"><div><span class="eyebrow">CASINO 9909</span><h3>Poker & Automaten</h3></div><span class="status-pill">Bargeld ${money(engine.state.resources.money)}</span></div><div class="slots">${slots}</div><div class="subsection">${poker}</div>`;
  }

  function renderLog(){
    $('#logPanel').innerHTML=`<div class="section-head"><div><span class="eyebrow">CHRONIK</span><h3>${engine.state.history.length} Meldungen</h3></div></div><div class="event-log">${engine.state.history.map((ev)=>`<article class="event ${esc(ev.type)}"><span>Z${ev.turn}</span><p>${esc(ev.text)}</p></article>`).join('')}</div>`;
    $('#tickerText').textContent=engine.state.history[0]?.text||'Keine Meldung.';
  }

  function renderPersonDialog(memberId){
    const m=engine.getMember(memberId);if(!m){$('#personDialog').close();return;}activePersonId=memberId;const st=engine.getMemberStatus(m),gear=m.equippedGearIds.map((id)=>{const item=engine.state.inventory.find((x)=>x.id===id);return DATA.gear.find((g)=>g.id===item?.gearId)?.title;}).filter(Boolean);
    const taskCards=DATA.autonomousTasks.map((t)=>{const opts=taskTargetOptions(t.targetType);return`<div class="info-card"><div class="row-between"><b>${esc(t.icon)} · ${esc(t.title)}</b><span class="tag">${esc(SKILL_LABELS[t.skill]||t.skill)}</span></div><p class="muted">${esc(t.description)}</p>${t.targetType!=='none'?`<select class="select" id="tasktarget-${t.id.replace(/\./g,'-')}">${opts}</select>`:''}<button class="mini-btn good" data-assign-task="${t.id}" data-member-id="${m.id}">Dauerhaft zuweisen</button></div>`;}).join('');
    const inventory=engine.state.inventory.filter((i)=>!i.equippedBy||i.equippedBy===m.id).map((item)=>{const def=DATA.gear.find((g)=>g.id===item.gearId);return`<div class="info-card"><div class="row-between"><b>${esc(def?.title||'Ausrüstung')}</b><span class="tag">${item.equippedBy===m.id?'ausgerüstet':'frei'}</span></div><button class="mini-btn" data-equip-item="${item.id}" data-member-id="${m.id}">${item.equippedBy===m.id?'Neu zuweisen':'Ausrüsten'}</button></div>`;}).join('')||'<p class="muted">Keine verfügbare Ausrüstung. Im Schwarzmarkt kaufen.</p>';
    const arts=DATA.martialArts.map((a)=>{const learned=m.martialArts.find((x)=>x.artId===a.id);return`<div class="info-card"><div class="row-between"><b>${esc(a.title)}</b><span class="status-pill">${learned?`Rang ${learned.rank}`:money(a.cost)}</span></div><div class="card-meta">${Object.entries(a.skillXp).map(([k,v])=>`<span class="tag">${esc(SKILL_LABELS[k])} +XP</span>`).join('')}</div><button class="mini-btn good" data-train-art="${a.id}" data-member-id="${m.id}">Trainieren</button></div>`;}).join('');
    $('#personDialogContent').innerHTML=`<div class="person-hero"><div class="avatar">${esc(initials(m.name))}</div><div><span class="eyebrow">PERSONENAKTE</span><h2>${esc(m.name)}</h2><p class="muted">${esc(m.role)} · ${esc(m.trait)} · ${m.age} Jahre · aus ${esc(m.origin)}</p><p>${esc(m.bio)}</p></div><span class="status-pill ${st.key==='injured'?'red':st.key==='ready'?'':'cyan'}">${esc(st.label)}</span></div>${st.key==='asset'?`<button class="mini-btn danger" data-unassign-asset-member="${m.id}">Aus Betrieb abziehen</button>`:''}<div class="detail-columns"><section><h3>Skills aus Praxis</h3><div class="skill-grid">${Object.entries(m.skills).map(([k,v])=>skillBar(SKILL_LABELS[k]||k,v,m.skillXp[k]||0)).join('')}</div><div class="summary-grid"><div><span>Macht</span><strong>${m.power}</strong></div><div><span>Treue</span><strong>${m.loyalty}</strong></div><div><span>Einsätze</span><strong>${m.missions}</strong></div><div><span>Siege</span><strong>${m.wins}</strong></div></div><h3 style="margin-top:12px">Ausrüstung</h3><p class="muted">Aktiv: ${esc(gear.join(', ')||'keine')}</p><div class="card-grid">${inventory}</div><h3 style="margin-top:12px">Kampfsport</h3><div class="card-grid">${arts}</div></section><section><div class="row-between"><h3>Autonomer Dauerauftrag</h3>${m.assignment?`<button class="mini-btn danger" data-clear-task="${m.id}">Beenden</button>`:''}</div>${m.assignment?`<div class="warning">Aktiv: ${esc(engine.getTaskLabel(m.assignment.taskId))} · Fortschritt ${m.assignment.progress}% · Zyklen ${m.assignment.cycles}</div>`:''}<div class="card-grid">${taskCards}</div><h3 style="margin-top:12px">Karriere & Entwicklung</h3><div class="career-list">${m.career.length?m.career.map((c)=>`<div class="career-item">Z${c.turn} · ${esc(c.text)}</div>`).join(''):'<p class="muted">Noch keine Karriereereignisse.</p>'}</div></section></div>`;
  }
  function taskTargetOptions(type){if(type==='asset')return engine.state.assets.map((a)=>`<option value="${a.id}">${esc(engine.getAssetDefinition(a.propertyId)?.title||a.id)} · ${esc(engine.getLocation(a.locationId).title)}</option>`).join('');if(type==='location')return DATA.world.locations.map((l)=>`<option value="${l.id}">${esc(l.title)}</option>`).join('');if(type==='company')return DATA.companies.map((c)=>`<option value="${c.id}">${esc(c.symbol)} · ${esc(c.name)}</option>`).join('');if(type==='institution')return DATA.institutions.map((i)=>`<option value="${i.id}">${esc(i.title)}</option>`).join('');return'';}

  function openCombatPreparation(){combatSelection=new Set(engine.getFreeCrew().slice(0,3).map((m)=>m.id));$('#combatDialog').showModal();renderCombatDialog();}
  function renderCombatDialog(){
    const container=$('#combatDialogContent'),session=engine.state.combatSession;
    if(!session){const free=engine.getFreeCrew(),ids=[...combatSelection],preview=engine.getCombatPreview('raid',ids);container.innerHTML=`<span class="eyebrow">KAMPFVORBEREITUNG</span><h2>${esc(engine.getLocation().title)} · gegen ${esc(preview?.rivalName||'Rivalen')}</h2><p class="muted">Wähle bis zu vier freie Crewmitglieder. Personenskill, Ausrüstung, Analyse, Gelände und Aufklärung fließen in die Prognose ein.</p><div class="combat-info-grid"><div><span>Siegchance</span><b>${preview?.percent||0}%</b></div><div><span>Deine Kraft</span><b>${preview?.attackerPower||0}</b></div><div><span>Gegner</span><b>${preview?.defenderPower||0}</b></div><div><span>Gelände</span><b>${esc(preview?.terrainLabel||'-')}</b></div><div><span>Verletzungsrisiko</span><b>${preview?.injuryRisk||0}%</b></div></div><h3 style="margin-top:12px">Crewbeiträge</h3><div class="crew-select-grid">${free.map((m)=>{const score=Math.round(engine.getCombatCrewScore(m));return`<div class="crew-select ${combatSelection.has(m.id)?'selected':''}" data-combat-select="${m.id}"><b>${esc(m.name)}</b><p class="muted">${esc(m.role)} · Kampf ${m.skills.combat} · Analyse ${m.skills.analysis}</p><span class="tag">Beitrag ${score}</span></div>`;}).join('')}</div><div class="button-row"><button class="btn" data-close="combatDialog">Abbrechen</button><button class="btn" data-combat-start ${combatSelection.size?'':'disabled'}>Kampf starten</button></div>`;return;}
    const preview=session.preview;container.innerHTML=`<span class="eyebrow">TAKTISCHER KAMPF · RUNDE ${session.round}/${session.maxRounds}</span><h2>${esc(engine.getLocation(session.locationId).title)} · ${esc(preview.rivalName)}</h2><div class="combat-hud"><div class="morale"><span class="muted">Crew-Moral</span><strong>${session.playerMorale}</strong><div class="bar"><i style="width:${session.playerMorale}%"></i></div></div><div class="combat-vs">VS</div><div class="morale"><span class="muted">Rivalen-Moral</span><strong>${session.enemyMorale}</strong><div class="bar"><i style="width:${session.enemyMorale}%;background:var(--red)"></i></div></div></div><div class="combat-stage"><div class="combat-lines"></div><div class="combat-side player">${session.crewIds.map((id)=>{const m=engine.getMember(id);return`<div class="fighter player" data-fighter-player><span>${esc(initials(m.name))}</span></div>`;}).join('')}</div><div class="combat-side enemy">${Array.from({length:Math.max(2,Math.min(5,Math.ceil(preview.defenderPower/45)))},(_,i)=>`<div class="fighter enemy" data-fighter-enemy>R${i+1}</div>`).join('')}</div></div><div class="combat-info-grid"><div><span>Taktikvorteil</span><b>${session.advantage>=0?'+':''}${session.advantage}</b></div><div><span>Deckung</span><b>${session.cover}</b></div><div><span>Gelände</span><b>${esc(preview.terrainLabel)}</b></div><div><span>Aufklärung</span><b>${preview.intel}</b></div><div><span>Risiko</span><b>${preview.injuryRisk}%</b></div></div><div class="button-row"><button class="btn" data-combat-decision="attack">Angriff</button><button class="btn" data-combat-decision="cover">Deckung</button><button class="btn" data-combat-decision="retreat">Rückzug</button></div><div class="combat-log">${session.log.slice().reverse().map((x)=>`<div>${esc(x)}</div>`).join('')}</div>`;
  }

  function switchTab(name){$$('.tab').forEach((t)=>t.classList.toggle('active',t.dataset.tab===name));$$('.tab-panel').forEach((p)=>{const on=p.dataset.panel===name;p.hidden=!on;p.classList.toggle('active',on);});}

  document.addEventListener('click',(event)=>{
    const t=event.target.closest('button,[data-location],[data-member],[data-combat-select]');if(!t)return;
    if(t.dataset.close){const d=$(`#${t.dataset.close}`);if(d?.open)d.close();return;}
    if(t.dataset.tab){switchTab(t.dataset.tab);return;}
    if(t.dataset.openTab){switchTab(t.dataset.openTab);return;}
    if(t.dataset.location){engine.selectLocation(t.dataset.location);renderMap();renderDistrict();return;}
    if(t.dataset.member){activePersonId=t.dataset.member;renderPersonDialog(activePersonId);$('#personDialog').showModal();return;}
    if(t.dataset.gameAction){if(t.dataset.gameAction==='raid'){openCombatPreparation();return;}mutate(engine.applyAction(t.dataset.gameAction));return;}
    if(t.dataset.travelTo){mutate(engine.travelTo(t.dataset.travelTo,t.dataset.travelMode),`Reise nach ${engine.getLocation(t.dataset.travelTo).title}`);return;}
    if(t.dataset.buyProperty){mutate(engine.buyProperty(t.dataset.buyProperty));return;}
    if(t.dataset.upgradeAsset){mutate(engine.upgradeProperty(t.dataset.upgradeAsset));return;}
    if(t.dataset.sellAsset){mutate(engine.sellProperty(t.dataset.sellAsset));return;}
    if(t.dataset.assignAssetCrew){const select=$(`#${CSS.escape('assetcrew-'+t.dataset.assignAssetCrew)}`);mutate(engine.assignCrewToAsset(t.dataset.assignAssetCrew,select?.value));return;}
    if(t.dataset.unassignAssetMember){mutate(engine.unassignCrewFromAsset(t.dataset.unassignAssetMember));return;}
    if(t.dataset.buyGear){mutate(engine.buyGear(t.dataset.buyGear));return;}
    if(t.dataset.equipItem){mutate(engine.equipGear(t.dataset.equipItem,t.dataset.memberId));return;}
    if(t.dataset.trainArt){mutate(engine.trainMartialArt(t.dataset.memberId,t.dataset.trainArt));return;}
    if(t.dataset.assignTask){const task=DATA.autonomousTasks.find((x)=>x.id===t.dataset.assignTask);const id=`tasktarget-${task.id.replace(/\./g,'-')}`;const target=task.targetType==='none'?null:$(`#${CSS.escape(id)}`)?.value;mutate(engine.assignCrewTask(t.dataset.memberId,t.dataset.assignTask,target));return;}
    if(t.dataset.clearTask){mutate(engine.clearCrewTask(t.dataset.clearTask));return;}
    if('bankDeposit' in t.dataset){mutate(engine.depositToBank(Number($('#bankDepositAmount').value)));return;}
    if('bankWithdraw' in t.dataset){mutate(engine.withdrawFromBank(Number($('#bankWithdrawAmount').value)));return;}
    if(t.dataset.buyShares){mutate(engine.buyShares(t.dataset.buyShares,Number(t.dataset.shares)));return;}
    if(t.dataset.sellShares){mutate(engine.sellShares(t.dataset.sellShares,Number(t.dataset.shares)));return;}
    if(t.dataset.plantMole){const select=$(`#${CSS.escape('mole-'+t.dataset.plantMole)}`);mutate(engine.plantMole(select?.value,t.dataset.plantMole));return;}
    if(t.dataset.removeMole){mutate(engine.removeMole(t.dataset.removeMole));return;}
    if(t.dataset.startStreet){mutate(engine.startStreetOperation(t.dataset.startStreet,engine.state.currentLocationId));return;}
    if(t.dataset.startContract){mutate(engine.startStreetOperation(t.dataset.startContract,$('#contractRival')?.value));return;}
    if(t.dataset.spinSlot){const bet=Number($(`#${CSS.escape('bet-'+t.dataset.spinSlot)}`).value);const r=engine.spinSlot(t.dataset.spinSlot,bet);if(r.ok){renderAll();saveState();setTimeout(()=>$$('.reel').forEach((x)=>x.classList.add('spin')),0);}else notify(r.reason);return;}
    if('pokerStart' in t.dataset){mutate(engine.startPoker(Number($('#pokerBet').value)));return;}
    if(t.dataset.pokerHold!==undefined){engine.togglePokerHold(Number(t.dataset.pokerHold));renderCasino();saveState();return;}
    if('pokerDraw' in t.dataset){mutate(engine.drawPoker());return;}
    if('pokerFinish' in t.dataset){mutate(engine.finishPoker());return;}
    if(t.dataset.combatSelect){if(combatSelection.has(t.dataset.combatSelect))combatSelection.delete(t.dataset.combatSelect);else if(combatSelection.size<4)combatSelection.add(t.dataset.combatSelect);renderCombatDialog();return;}
    if('combatStart' in t.dataset){const r=engine.startCombat('raid',[...combatSelection]);if(!r.ok){notify(r.reason);return;}renderCombatDialog();saveState();return;}
    if(t.dataset.combatDecision){const before=t.dataset.combatDecision;const r=engine.combatDecision(before);if(!r.ok){notify(r.reason);return;}if(r.finished){renderAll();saveState();$('#combatDialogContent').innerHTML=`<span class="eyebrow">KAMPFERGEBNIS</span><h2>${r.result.outcome==='win'?'SIEG':r.result.outcome==='loss'?'NIEDERLAGE':'RÜCKZUG'}</h2><div class="combat-info-grid"><div><span>Runden</span><b>${r.result.rounds}</b></div><div><span>Belohnung</span><b>${money(r.result.reward)}</b></div><div><span>Crew-Moral</span><b>${r.result.playerMorale}</b></div><div><span>Rivalen-Moral</span><b>${r.result.enemyMorale}</b></div><div><span>Übernahme</span><b>${r.result.takeover?'JA':'NEIN'}</b></div></div><div class="combat-log">${r.result.log.slice().reverse().map((x)=>`<div>${esc(x)}</div>`).join('')}</div><button class="btn" data-close="combatDialog">Schließen</button>`;}else{renderCombatDialog();setTimeout(()=>{const cls=before==='attack'?'attack':'cover';$$('[data-fighter-player]').forEach((x)=>x.classList.add(cls));if(before==='attack')$$('[data-fighter-enemy]').forEach((x)=>x.classList.add('attack'));},0);}return;}
  });

  $('#helpButton').addEventListener('click',()=>$('#helpDialog').showModal());
  $('#saveButton').addEventListener('click',()=>saveState(true));
  $('#resetButton').addEventListener('click',()=>{if(!confirm('Neues Spiel starten? Der lokale Spielstand wird ersetzt.'))return;[STORAGE_KEY,...LEGACY_KEYS].forEach((k)=>localStorage.removeItem(k));location.reload();});
  $$('.modal').forEach((d)=>d.addEventListener('click',(e)=>{if(e.target===d)d.close();}));
  $('#cityMap').addEventListener('keydown',(event)=>{const node=event.target.closest('[data-location]');if(node&&(event.key==='Enter'||event.key===' ')){event.preventDefault();engine.selectLocation(node.dataset.location);renderMap();renderDistrict();}});

  renderAll();
})();
