(function(root){
  'use strict';
  const engine=root.LIVING_CITY_05_ENGINE||root.REVIVAL_GAME_ENGINE;
  const DATA=root.GAME_DATA;if(!engine||!DATA)return;
  const $=(s)=>document.querySelector(s),$$=(s)=>Array.from(document.querySelectorAll(s));
  const esc=(v)=>String(v??'').replace(/[&<>"']/g,(m)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const money=(v)=>`${Number(v||0).toLocaleString('de-DE',{maximumFractionDigits:0})} €`;
  const world=Object.fromEntries(DATA.world.locations.map((l)=>[l.id,l]));
  let view={x:0,y:0,w:1000,h:700},drag=null,helpOpen=false,wrapped=false;
  const MIN_ZOOM=1,MAX_ZOOM=4.2;
  function clampView(){view.w=Math.max(1000/MAX_ZOOM,Math.min(1000/MIN_ZOOM,view.w));view.h=view.w*.7;view.x=Math.max(0,Math.min(1000-view.w,view.x));view.y=Math.max(0,Math.min(700-view.h,view.y));}
  function applyView(){const svg=$('#cityMap');if(!svg)return;clampView();svg.setAttribute('viewBox',`${view.x.toFixed(1)} ${view.y.toFixed(1)} ${view.w.toFixed(1)} ${view.h.toFixed(1)}`);svg.dataset.zoom=(1000/view.w).toFixed(2);}
  function fitMap(){view={x:0,y:0,w:1000,h:700};applyView();}
  function centerLocation(id,zoom=Math.max(1.8,1000/view.w)){const l=world[id];if(!l)return;const w=1000/Math.min(MAX_ZOOM,Math.max(MIN_ZOOM,zoom)),h=w*.7;view={x:l.x-w/2,y:l.y-h/2,w,h};applyView();}
  function zoomAt(factor,clientX,clientY){const svg=$('#cityMap');if(!svg)return;const rect=svg.getBoundingClientRect(),px=rect.width?Math.max(0,Math.min(1,(clientX-rect.left)/rect.width)):.5,py=rect.height?Math.max(0,Math.min(1,(clientY-rect.top)/rect.height)):.5;const anchorX=view.x+px*view.w,anchorY=view.y+py*view.h,newW=Math.max(1000/MAX_ZOOM,Math.min(1000,view.w/factor)),newH=newW*.7;view={x:anchorX-px*newW,y:anchorY-py*newH,w:newW,h:newH};applyView();}
  function pan(dx,dy){view.x+=dx*view.w;view.y+=dy*view.h;applyView();}
  function directOptions(){return engine.getTravelOptions().slice().sort((a,b)=>a.cost-b.cost||a.title.localeCompare(b.title,'de'));}
  function graphPath(from,to){if(from===to)return[];const g={};const add=(a,b,mode)=>{(g[a]||=[]).push({to:b,mode});};DATA.world.connections.forEach(([a,b])=>{add(a,b,'street');add(b,a,'street');});(DATA.world.trainRoutes||[]).forEach((r)=>add(r.from,r.to,'train'));const q=[from],seen=new Set([from]),prev={};while(q.length){const at=q.shift();for(const e of g[at]||[]){if(seen.has(e.to))continue;seen.add(e.to);prev[e.to]={from:at,mode:e.mode};if(e.to===to){q.length=0;break;}q.push(e.to);}}if(!prev[to])return[];const path=[];let cur=to;while(cur!==from){const s=prev[cur];path.unshift({from:s.from,to:cur,mode:s.mode});cur=s.from;}return path;}
  function primaryTask(){
    if(engine.state.combatSession)return{icon:'⚔',label:'Kampf offen',title:'Kampfentscheidung fortsetzen',hint:'Der Zug bleibt gesperrt, bis du entscheidest.',action:'combat'};
    if(engine.state.poker?.active)return{icon:'♠',label:'Poker offen',title:'Pokerrunde abschließen',hint:'Öffne Casino und beende die laufende Hand.',tab:'casino'};
    const summary=typeof engine.getDirectorSummary==='function'?engine.getDirectorSummary():null,active=(summary?.missions?.active||[]).slice().sort((a,b)=>(a.progress?.remaining??99)-(b.progress?.remaining??99));
    if(active.length){const m=active[0],p=m.progress||engine.getMissionProgress?.(m);return{icon:m.icon||'◆',label:`Aktiver Auftrag · ${p?.remaining??'?'} Züge`,title:m.title,hint:`Fortschritt ${p?.current??0}/${p?.target??0}`,tab:'director'};}
    if(summary?.missions?.offers?.length)return{icon:'◇',label:'Neue Gelegenheit',title:'Einen Auftrag im Direktor wählen',hint:`${summary.missions.offers.length} Angebote warten.`,tab:'director'};
    return{icon:'◎',label:'Nächster Schritt',title:'Bezirk auswählen und Route prüfen',hint:'Direktziele stehen unmittelbar über der Karte.',action:'map'};
  }
  function renderDashboard(){const el=$('#focusDashboard');if(!el)return;const task=primaryTask(),current=engine.getLocation(engine.state.currentLocationId),selected=engine.getLocation(engine.state.selectedLocationId),opts=directOptions(),direct=opts.find((o)=>o.to===selected.id),warnings=engine.getDecisionSupport?.().warnings||[],summary=engine.getDirectorSummary?.();el.innerHTML=`<article class="focus-card priority"><span class="focus-icon">${esc(task.icon)}</span><div class="focus-copy"><span>${esc(task.label)}</span><b>${esc(task.title)}</b><small>${esc(task.hint)}</small></div>${task.tab?`<button class="mini-btn good" data-open-tab="${task.tab}">Öffnen</button>`:`<button class="mini-btn good" data-lc05b-action="${task.action||'map'}">Zeigen</button>`}</article><article class="focus-card"><span class="focus-icon">⌖</span><div class="focus-copy"><span>Standort</span><b>${esc(current.title)}</b><small>${selected.id===current.id?'Du bist hier':`Auswahl: ${esc(selected.title)}`}</small></div><button class="mini-btn" data-lc05b-action="current">Zentrieren</button></article><article class="focus-card"><span class="focus-icon">⇢</span><div class="focus-copy"><span>Reise</span><b>${direct?`${esc(selected.title)} · direkt`:selected.id===current.id?'Ziel auswählen':`${esc(selected.title)} · Route`}</b><small>${direct?`${direct.mode==='train'?'Bahn':'Straße'} · ${money(direct.cost)}`:`${opts.length} Direktziele verfügbar`}</small></div><button class="mini-btn" data-lc05b-action="map">Karte</button></article><article class="focus-card"><span class="focus-icon">${warnings.length?'!':'○'}</span><div class="focus-copy"><span>${warnings.length?'Achtung':'Stadtstatus'}</span><b class="${warnings.length?'focus-alert':''}">${esc(warnings[0]||`${summary?.phase?.label||'Stadt'} · Spannung ${summary?.tension??0}`)}</b><small>${warnings.length>1?`+ ${warnings.length-1} weitere Hinweise`:'Keine akute Blockade.'}</small></div><button class="mini-btn" data-lc05b-action="help">Hilfe</button></article>`;}
  function renderDirectTargets(){const el=$('#mapDirectTargets');if(!el)return;const opts=directOptions();el.innerHTML=`<span class="direct-label">Direkt erreichbar</span>${opts.length?opts.map((o)=>`<button class="direct-target" data-lc05b-select="${esc(o.to)}" title="Ziel auswählen: ${esc(o.title)}">${o.mode==='train'?'▤':'→'} ${esc(o.title)} <b>${money(o.cost)}</b></button>`).join(''):'<span class="muted">Keine direkte Verbindung.</span>'}`;}
  function helpMarkup(){const selected=engine.getLocation(engine.state.selectedLocationId),current=engine.getLocation(engine.state.currentLocationId),opts=directOptions(),direct=opts.find((o)=>o.to===selected.id),path=graphPath(current.id,selected.id),task=primaryTask();return`<article class="help-step next"><strong>1 · Jetzt sinnvoll</strong><p>${esc(task.title)} — ${esc(task.hint)}</p></article><article class="help-step"><strong>2 · Reisen</strong><p>${selected.id===current.id?'Klicke auf einen Bezirk oder eines der Direktziele oberhalb der Karte.':direct?`${selected.title} ist direkt erreichbar. Der große Reisebutton oberhalb der Karte führt sofort hin.`:path.length?`${selected.title} benötigt ${path.length} Etappen. Der Reisebereich zeigt automatisch den nächsten Halt.`:'Für dieses Ziel ist aktuell keine Route verfügbar.'}</p></article><article class="help-step"><strong>3 · Karte bewegen</strong><p>Karte mit gedrückter Maus ziehen. Mit Mausrad oder +/− zoomen. Ein Doppelklick auf einen Bezirk zentriert ihn.</p></article><article class="help-step"><strong>Tastatur</strong><div class="key-grid"><span><kbd>M</kbd>Karte fokussieren</span><span><kbd>H</kbd>Hilfe ein/aus</span><span><kbd>R</kbd>gewählte Reise starten</span><span><kbd>E</kbd>Zug beenden</span><span><kbd>WASD</kbd>Karte bewegen</span><span><kbd>+/−</kbd>zoomen</span></div></article>`;}
  function renderHelp(){const dock=$('#helpDock'),wb=$('#mapWorkbench'),btn=$('#helpButton');if(!dock||!wb)return;dock.hidden=!helpOpen;wb.classList.toggle('help-open',helpOpen);btn?.setAttribute('aria-expanded',String(helpOpen));if(helpOpen)$('#helpDockBody').innerHTML=helpMarkup();requestAnimationFrame(()=>applyView());}
  function toggleHelp(force){helpOpen=typeof force==='boolean'?force:!helpOpen;renderHelp();}
  function focusMap(){const svg=$('#cityMap');svg?.focus({preventScroll:true});$('#mapStage')?.scrollIntoView?.({block:'nearest',behavior:'smooth'});}
  function rebuildControls(){const controls=[['mapZoomOut',()=>zoomAt(1/1.22,innerWidth/2,innerHeight/2)],['mapZoomReset',fitMap],['mapZoomIn',()=>zoomAt(1.22,innerWidth/2,innerHeight/2)]];controls.forEach(([id,fn])=>{const old=$(`#${id}`);if(!old)return;const fresh=old.cloneNode(true);old.replaceWith(fresh);fresh.addEventListener('click',(e)=>{e.preventDefault();fn();});});}
  function replaceHelpButton(){const old=$('#helpButton');if(!old||old.dataset.lc05b)return;const fresh=old.cloneNode(true);fresh.dataset.lc05b='1';old.replaceWith(fresh);fresh.addEventListener('click',(e)=>{e.preventDefault();toggleHelp();});$('#helpDockClose')?.addEventListener('click',()=>toggleHelp(false));}
  function installMapInteraction(){const svg=$('#cityMap'),stage=$('#mapStage');if(!svg||svg.dataset.lc05bPan)return;svg.dataset.lc05bPan='1';stage?.addEventListener('pointerdown',(e)=>{if(e.button!==0||e.target.closest?.('.district-node'))return;drag={x:e.clientX,y:e.clientY,startX:view.x,startY:view.y};stage.classList.add('is-panning');stage.setPointerCapture?.(e.pointerId);e.preventDefault();});stage?.addEventListener('pointermove',(e)=>{if(!drag)return;const rect=svg.getBoundingClientRect();view.x=drag.startX-(e.clientX-drag.x)*(view.w/Math.max(1,rect.width));view.y=drag.startY-(e.clientY-drag.y)*(view.h/Math.max(1,rect.height));applyView();});const stop=(e)=>{if(!drag)return;drag=null;stage.classList.remove('is-panning');stage.releasePointerCapture?.(e.pointerId);};stage?.addEventListener('pointerup',stop);stage?.addEventListener('pointercancel',stop);stage?.addEventListener('wheel',(e)=>{e.preventDefault();zoomAt(e.deltaY<0?1.16:1/1.16,e.clientX,e.clientY);},{passive:false});svg.addEventListener('dblclick',(e)=>{const node=e.target.closest?.('[data-location]');if(node){centerLocation(node.dataset.location,Math.max(2.2,1000/view.w));e.preventDefault();}});svg.addEventListener('keydown',(e)=>{const k=e.key.toLowerCase();if(['arrowleft','a','arrowright','d','arrowup','w','arrowdown','s','+','=','-','_','home','0'].includes(k)){if(k==='arrowleft'||k==='a')pan(-.12,0);else if(k==='arrowright'||k==='d')pan(.12,0);else if(k==='arrowup'||k==='w')pan(0,-.12);else if(k==='arrowdown'||k==='s')pan(0,.12);else if(k==='+'||k==='=')zoomAt(1.2,innerWidth/2,innerHeight/2);else if(k==='-'||k==='_')zoomAt(1/1.2,innerWidth/2,innerHeight/2);else fitMap();e.preventDefault();}});}
  function wrapMapRender(){if(wrapped||!root.LIVING_CITY_04A?.renderMap)return;const base=root.LIVING_CITY_04A.renderMap;root.LIVING_CITY_04A.renderMap=function(){const r=base.apply(this,arguments);applyView();renderDirectTargets();renderDashboard();if(helpOpen)renderHelp();return r;};wrapped=true;}
  function render(){renderDashboard();renderDirectTargets();if(helpOpen)renderHelp();applyView();}
  function init(){replaceHelpButton();rebuildControls();installMapInteraction();wrapMapRender();render();document.body.dataset.livingCity='05b';}
  document.addEventListener('click',(e)=>{const t=e.target.closest?.('[data-lc05b-select],[data-lc05b-action]');if(!t)return;if(t.dataset.lc05bSelect){engine.selectLocation(t.dataset.lc05bSelect);root.LIVING_CITY_04A?.renderMap?.();centerLocation(t.dataset.lc05bSelect,Math.max(1.55,1000/view.w));root.GAME_UI_REFRESH?.schedule?.();return;}const a=t.dataset.lc05bAction;if(a==='help')toggleHelp();else if(a==='map')focusMap();else if(a==='current'){centerLocation(engine.state.currentLocationId,2.1);focusMap();}else if(a==='combat'){$('#combatDialog')?.showModal?.();}});
  document.addEventListener('keydown',(e)=>{const tag=e.target?.tagName;if(['INPUT','SELECT','TEXTAREA'].includes(tag)||e.ctrlKey||e.metaKey||e.altKey||document.querySelector('dialog[open]'))return;const k=e.key.toLowerCase();if(k==='h'){e.preventDefault();toggleHelp();}else if(k==='m'){e.preventDefault();focusMap();}else if(k==='r'){const btn=$('#mapQuickbar [data-travel-to]');if(btn){e.preventDefault();btn.click();}}});
  root.LIVING_CITY_05B_UI=Object.freeze({render,fitMap,centerLocation,toggleHelp});init();
})(typeof globalThis!=='undefined'?globalThis:this);
