(function(root){
  'use strict';
  const engine=root.LIVING_CITY_05_ENGINE||root.REVIVAL_GAME_ENGINE;
  const DATA=root.GAME_DATA;if(!engine||!DATA)return;
  const $=(s)=>document.querySelector(s),esc=(v)=>String(v??'').replace(/[&<>"']/g,(m)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  let audio=null,osc=null,gain=null;
  function ensureShell(){
    const toolbar=document.querySelector('.map-toolbar-actions');if(toolbar&&!$('#lc05MapLayers')){const layers=document.createElement('div');layers.id='lc05MapLayers';layers.className='map-layers';layers.innerHTML='<button data-map-layer="ownership">Gebiete</button><button data-map-layer="pressure">Druck</button><button data-map-layer="economy">Wirtschaft</button><button data-map-layer="events">Ereignisse</button>';toolbar.prepend(layers);}
    const mapPanel=document.querySelector('.map-panel'),ticker=mapPanel?.querySelector('.ticker');if(mapPanel&&ticker&&!$('#lc05SceneStrip')){const strip=document.createElement('div');strip.id='lc05SceneStrip';strip.className='scene-strip';ticker.before(strip);}
    if(!$('#sceneDialog')){const dialog=document.createElement('dialog');dialog.id='sceneDialog';dialog.className='modal scene-modal';dialog.innerHTML='<div class="modal-card wide"><button class="modal-close" data-close="sceneDialog">×</button><div id="sceneDialogContent"></div></div>';document.body.appendChild(dialog);}
    if(!$('#missionBriefingDialog')){const dialog=document.createElement('dialog');dialog.id='missionBriefingDialog';dialog.className='modal briefing-modal';dialog.innerHTML='<div class="modal-card"><button class="modal-close" data-close="missionBriefingDialog">×</button><div id="missionBriefingContent"></div></div>';document.body.appendChild(dialog);}
    document.body.dataset.livingCity='05';
  }
  function persist(){try{const raw=engine.exportState();localStorage.setItem('pppoppi-bunkerwahrheit-html-v0110',raw);localStorage.setItem('pppoppi-bunkerwahrheit-html-v0100',raw);}catch(_){}}
  function renderSceneStrip(){const el=$('#lc05SceneStrip');if(!el)return;const scene=engine.getInterior(engine.state.selectedLocationId),here=engine.state.selectedLocationId===engine.state.currentLocationId;el.innerHTML=`<div><span class="eyebrow">ORTSSZENE</span><strong>${esc(scene.title)}</strong><small>${esc(scene.subtitle)}</small></div><div class="scene-actions"><button class="mini-btn ${here?'good':''}" data-open-interior="${scene.locationId}">${here?'Innenansicht öffnen':'Vorschau'}</button><button class="mini-btn" id="ambientToggle">${audio?'Atmosphäre an':'Atmosphäre aus'}</button></div>`;}
  function renderScene(locationId){const scene=engine.recordInteriorOpen(locationId),content=$('#sceneDialogContent');if(!content)return;content.innerHTML=`<div class="scene-hero theme-${esc(scene.theme)}"><div class="scene-depth back"></div><div class="scene-depth mid"></div><div class="scene-depth front"></div><div class="scene-sign"><span>${esc(scene.locationTitle)}</span><strong>${esc(scene.title)}</strong></div>${scene.hotspots.map((h,i)=>`<article class="scene-hotspot h${i+1}"><i>${esc(h[1])}</i><b>${esc(h[0])}</b><small>${esc(h[2])}</small></article>`).join('')}</div><div class="scene-summary"><div><span>Besitzer</span><b>${esc(scene.owner)}</b></div><div><span>Kontrolle</span><b>${scene.control}%</b></div><div><span>Polizei</span><b>${scene.police}%</b></div><div><span>Rivalen</span><b>${scene.rival}%</b></div><div><span>Eigene Betriebe</span><b>${scene.assets}</b></div><div><span>Atmosphäre</span><b>${esc(scene.ambient?.label||'Stadtklang')}</b></div></div>${scene.company?`<div class="scene-company"><span>Lokales Unternehmen</span><strong>${esc(scene.company.name)}</strong><b>${scene.company.price} €</b></div>`:''}${scene.events.length?`<div class="scene-alert">Aktiv: ${scene.events.map((e)=>esc(e.definition?.title||'Ereignis')).join(', ')}</div>`:''}`;$('#sceneDialog').showModal();persist();}
  function renderMapLayer(){const layer=engine.state.preferences.mapLayer||'ownership';document.body.dataset.mapLayer=layer;$$('#lc05MapLayers button').forEach((b)=>b.classList.toggle('active',b.dataset.mapLayer===layer));const svg=$('#cityMap');if(!svg)return;svg.querySelectorAll('.lc05-map-overlay').forEach((n)=>n.remove());const ns='http://www.w3.org/2000/svg',g=document.createElementNS(ns,'g');g.setAttribute('class','lc05-map-overlay');DATA.world.locations.forEach((loc)=>{const d=engine.getDistrict(loc.id);if(layer==='economy'){const company=DATA.companies.find((c)=>c.locationId===loc.id),assets=engine.state.assets.filter((a)=>a.locationId===loc.id).length;if(!company&&!assets)return;const t=document.createElementNS(ns,'text');t.setAttribute('x',loc.x+34);t.setAttribute('y',loc.y+35);t.setAttribute('class','lc05-economy-glyph');t.textContent=company?`${company.symbol} ${engine.state.market.companies[company.id]?.price||''}`:`B${assets}`;g.appendChild(t);}else if(layer==='pressure'){const c=document.createElementNS(ns,'circle');c.setAttribute('cx',loc.x);c.setAttribute('cy',loc.y);c.setAttribute('r',String(38+Math.round((d.rival+d.police)/12)));c.setAttribute('class',`lc05-pressure ${d.rival+d.police>115?'hot':''}`);g.appendChild(c);}else if(layer==='events'){const events=typeof engine.getCityEventsAt==='function'?engine.getCityEventsAt(loc.id):[];if(!events.length)return;const t=document.createElementNS(ns,'text');t.setAttribute('x',loc.x);t.setAttribute('y',loc.y-52);t.setAttribute('text-anchor','middle');t.setAttribute('class','lc05-event-label');t.textContent=events.map((e)=>e.definition?.icon||'!').join(' ');g.appendChild(t);}});svg.appendChild(g);}
  function renderRelations(){const panel=$('#crewPanel');if(!panel)return;let rel=$('#lc05Relations');if(!rel){rel=document.createElement('section');rel.id='lc05Relations';rel.className='lc05-relations';panel.appendChild(rel);}const pairs=engine.getCrewRelationsOverview();rel.innerHTML=`<div class="section-head"><div><span class="eyebrow">CREW-CHEMIE</span><h3>Beziehungen & Belastung</h3></div><span class="status-pill">${pairs.length} Paarungen</span></div><div class="relation-summary">${engine.state.gang.map((m)=>`<span>${esc(m.name)} <b>${m.morale}</b><small>Moral</small><i style="--stress:${m.stress}%"></i></span>`).join('')}</div><div class="crew-relation-list">${pairs.slice(0,6).map((r)=>`<article><div><b>${esc(r.aName)}</b><span>↔</span><b>${esc(r.bName)}</b></div><strong>${esc(r.label)} · ${r.value}</strong><small>${esc(r.lastChange)}</small><div class="crew-relation-actions"><button data-crew-interaction="talk" data-a="${r.a}" data-b="${r.b}">Reden</button><button data-crew-interaction="plan" data-a="${r.a}" data-b="${r.b}">Planen</button><button data-crew-interaction="spar" data-a="${r.a}" data-b="${r.b}">Sparring</button></div></article>`).join('')}</div>`;}
  function decoratePerson(){const dialog=$('#personDialog'),content=$('#personDialogContent');if(!dialog?.open||!content||content.querySelector('.lc05-person-relations'))return;const name=content.querySelector('h2')?.textContent,member=engine.state.gang.find((m)=>m.name===name);if(!member)return;const relations=engine.getCrewRelationsOverview(member.id);const box=document.createElement('section');box.className='lc05-person-relations';box.innerHTML=`<h3>Beziehungen & Belastung</h3><div class="summary-grid"><div><span>Moral</span><strong>${member.morale}</strong></div><div><span>Stress</span><strong>${member.stress}</strong></div></div><div class="person-rel-list">${relations.map((r)=>{const other=r.a===member.id?r.bName:r.aName;return`<div><b>${esc(other)}</b><span>${esc(r.label)} · ${r.value}</span></div>`;}).join('')}</div>`;content.appendChild(box);}
  function renderBriefings(){const panel=$('#revivalDirectorPanel');if(!panel)return;let box=$('#lc05Briefings');if(!box){box=document.createElement('section');box.id='lc05Briefings';box.className='revival-section lc05-briefings';panel.prepend(box);}const active=engine.state.missions.active;box.innerHTML=`<div class="section-title"><span class="eyebrow">BRIEFINGS</span><h3>Entscheidungen vor dem Einsatz</h3></div>${active.length?`<div class="briefing-list">${active.map((m)=>{const info=engine.getMissionBriefing(m.id);return`<article><div><b>${esc(m.title)}</b><small>${info?.advisor?`Advisor: ${esc(info.advisor.name)} · ${esc(info.skill)} ${info.advisor.level}`:'Crew analysiert'}</small></div><button class="mini-btn ${info?.resolved?'':'good'}" data-open-briefing="${m.id}" ${info?.resolved?'disabled':''}>${info?.resolved?'Entschieden':'Briefing'}</button></article>`;}).join('')}</div>`:'<div class="revival-empty compact">Noch kein aktiver Auftrag für ein Briefing.</div>'}`;}
  function openBriefing(id){const info=engine.getMissionBriefing(id);if(!info)return;const c=$('#missionBriefingContent');c.innerHTML=`<span class="eyebrow">MISSIONSBRIEFING</span><h2>${esc(info.mission.title)}</h2><p>${esc(info.mission.description)}</p><div class="briefing-advisor"><span>Advisor</span><strong>${esc(info.advisor?.name||'Crew')}</strong><small>${esc(info.skill)} · Stufe ${info.advisor?.level||'-'}</small></div><div class="briefing-choices">${info.choices.map((x)=>`<button data-briefing-choice="${x.id}" data-mission="${id}"><i>${esc(x.icon)}</i><b>${esc(x.title)}</b><small>${esc(x.description)}</small></button>`).join('')}</div>`;$('#missionBriefingDialog').showModal();}
  function setAmbient(on){engine.setAmbientEnabled(on);if(!on){try{osc?.stop();audio?.close();}catch(_){}audio=osc=gain=null;persist();renderSceneStrip();return;}try{audio=new (window.AudioContext||window.webkitAudioContext)();osc=audio.createOscillator();gain=audio.createGain();const profile=engine.getInterior(engine.state.currentLocationId).ambient||{tone:80,pulse:.1};osc.type='sine';osc.frequency.value=profile.tone||80;gain.gain.value=.018;osc.connect(gain);gain.connect(audio.destination);osc.start();}catch(_){engine.setAmbientEnabled(false);}persist();renderSceneStrip();}
  function render(){ensureShell();renderSceneStrip();renderMapLayer();renderRelations();decoratePerson();renderBriefings();}
  const $$=(s)=>Array.from(document.querySelectorAll(s));
  document.addEventListener('click',(event)=>{const t=event.target.closest?.('button,[data-open-interior]');if(!t)return;if(t.dataset.mapLayer){engine.setMapLayer(t.dataset.mapLayer);persist();renderMapLayer();return;}if(t.dataset.openInterior){renderScene(t.dataset.openInterior);return;}if(t.id==='ambientToggle'){setAmbient(!audio);return;}if(t.dataset.crewInteraction){const r=engine.runCrewInteraction(t.dataset.a,t.dataset.b,t.dataset.crewInteraction);$('#tickerText').textContent=r.ok?'Crew-Beziehung entwickelt.':r.reason;persist();if(r.ok)location.reload();else renderRelations();return;}if(t.dataset.openBriefing){openBriefing(t.dataset.openBriefing);return;}if(t.dataset.briefingChoice){const r=engine.resolveMissionBriefing(t.dataset.mission,t.dataset.briefingChoice);$('#tickerText').textContent=r.ok?`Briefing entschieden: ${r.choice.title}`:r.reason;if(r.ok){persist();$('#missionBriefingDialog').close();renderBriefings();}return;}setTimeout(render,0);});
  const observer=new MutationObserver((mutations)=>{let crew=false,director=false,person=false,map=false,strip=false;for(const m of mutations){const t=m.target;if(t?.id==='crewPanel'&&!$('#lc05Relations'))crew=true;if((t?.id==='revivalDirectorPanel'||t?.closest?.('#revivalDirectorPanel'))&&!$('#lc05Briefings'))director=true;if((t?.id==='personDialogContent'||t?.closest?.('#personDialogContent'))&&$('#personDialog')?.open&&!document.querySelector('.lc05-person-relations'))person=true;if((t?.id==='cityMap'||t?.closest?.('#cityMap'))&&!document.querySelector('#cityMap .lc05-map-overlay'))map=true;if(t?.id==='mapQuickbar'||t?.id==='mapCallout')strip=true;}if(crew)renderRelations();if(director)renderBriefings();if(person)decoratePerson();if(map)renderMapLayer();if(strip)renderSceneStrip();});observer.observe(document.body,{childList:true,subtree:true});
  root.LIVING_CITY_05_UI={render,renderMapLayer,renderRelations,renderScene};render();
})(typeof globalThis!=='undefined'?globalThis:this);
