(function(root,factory){
  const BASE=typeof module==='object'&&module.exports?require('./revival-engine.js'):root.GAME_ENGINE;
  const DATA=typeof module==='object'&&module.exports?require('./lc05-data.js'):root.GAME_DATA;
  const api=factory(BASE,DATA,root);
  if(typeof module==='object'&&module.exports)module.exports=api;else root.GAME_ENGINE=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(BASE,DATA,ROOT){
  'use strict';
  const {GameEngine:Parent,clamp}=BASE;
  const clone=(v)=>JSON.parse(JSON.stringify(v));
  const pairKey=(a,b)=>[a,b].sort().join('|');
  const relevantSkill=(category)=>({territory:'combat',conflict:'combat',business:'business',crew:'social',network:'stealth',city:'driving'}[category]||'analysis');
  class LivingCity05Engine extends Parent{
    constructor(options={}){super({...options,data:options.data||DATA});if(ROOT&&typeof ROOT==='object'){ROOT.LIVING_CITY_05_ENGINE=this;ROOT.REVIVAL_GAME_ENGINE=this;}}
    normalizeMember(member){const m=super.normalizeMember(member);if(!Number.isFinite(m.stress))m.stress=18;if(!Number.isFinite(m.morale))m.morale=Math.max(45,Math.min(92,Math.round((m.loyalty+60)/2)));return m;}
    createInitialState(){const state=super.createInitialState();state.crewRelations={};state.crewInteractions={};state.missionBriefings={};state.preferences={ambient:false,mapLayer:'ownership'};state.directorModifiers={tension:0,opportunity:0};Object.assign(state.stats,{relationshipTicks:0,crewInteractions:0,briefings:0,interiorsOpened:0});return state;}
    ensureStateShape(){super.ensureStateShape();if(!this.state.crewRelations)this.state.crewRelations={};if(!this.state.crewInteractions)this.state.crewInteractions={};if(!this.state.missionBriefings)this.state.missionBriefings={};if(!this.state.preferences)this.state.preferences={ambient:false,mapLayer:'ownership'};if(!this.state.directorModifiers)this.state.directorModifiers={tension:0,opportunity:0};if(!('ambient' in this.state.preferences))this.state.preferences.ambient=false;if(!this.state.preferences.mapLayer)this.state.preferences.mapLayer='ownership';['relationshipTicks','crewInteractions','briefings','interiorsOpened'].forEach((k)=>{if(!Number.isFinite(this.state.stats[k]))this.state.stats[k]=0;});this.state.gang.forEach((m)=>{if(!Number.isFinite(m.stress))m.stress=18;if(!Number.isFinite(m.morale))m.morale=Math.max(45,Math.min(92,Math.round((m.loyalty+60)/2)));});this.ensureCrewRelations();this.state.schema=this.data.schema;this.state.version=this.data.version;}
    ensureCrewRelations(){const valid=new Set(this.state.gang.map((m)=>m.id));Object.keys(this.state.crewRelations).forEach((key)=>{const r=this.state.crewRelations[key];if(!valid.has(r.a)||!valid.has(r.b))delete this.state.crewRelations[key];});for(let i=0;i<this.state.gang.length;i+=1)for(let j=i+1;j<this.state.gang.length;j+=1){const a=this.state.gang[i],b=this.state.gang[j],key=pairKey(a.id,b.id);if(!this.state.crewRelations[key]){const roleBonus=a.role===b.role?-2:(a.skills.social+b.skills.social>=13?5:0),value=clamp(42+Math.round((a.loyalty+b.loyalty)/8)+roleBonus,18,82);this.state.crewRelations[key]={a:a.id,b:b.id,value,tension:clamp(22-value/4,0,35),shared:0,lastChange:'Startbindung'};}}}
    getCrewRelation(a,b){this.ensureCrewRelations();return this.state.crewRelations[pairKey(a,b)]||null;}
    relationLabel(value){if(value>=82)return'Verbündet';if(value>=66)return'Eng verbunden';if(value>=50)return'Stabil';if(value>=34)return'Distanziert';if(value>=18)return'Angespannt';return'Zerwürfnis';}
    getCrewRelationsOverview(memberId=null){this.ensureCrewRelations();return Object.values(this.state.crewRelations).filter((r)=>!memberId||r.a===memberId||r.b===memberId).map((r)=>{const a=this.getMember(r.a),b=this.getMember(r.b);return{...clone(r),aName:a?.name||r.a,bName:b?.name||r.b,label:this.relationLabel(r.value)};}).sort((x,y)=>y.value-x.value);}
    adjustCrewRelation(a,b,delta,reason='Gemeinsame Erfahrung'){const r=this.getCrewRelation(a,b);if(!r)return null;r.value=clamp(r.value+delta,0,100);r.tension=clamp(r.tension-Math.sign(delta)*Math.min(6,Math.abs(delta)),0,100);r.lastChange=reason;if(delta>0)r.shared+=1;this.state.stats.relationshipTicks+=1;return clone(r);}
    resolveCrewRelations(){this.ensureCrewRelations();this.state.gang.forEach((m)=>{const st=this.getMemberStatus(m);let stressDelta=st.key==='assigned'||st.key==='mole'?2:st.key==='injured'?3:-2;if(m.assignment?.taskId==='task.rest')stressDelta=-8;m.stress=clamp(m.stress+stressDelta,0,100);m.morale=clamp(Math.round(m.loyalty*.62+(100-m.stress)*.38),0,100);if(m.stress>=82&&this.state.turn%3===0)m.loyalty=clamp(m.loyalty-1);});Object.values(this.state.crewRelations).forEach((r)=>{const a=this.getMember(r.a),b=this.getMember(r.b);if(!a||!b)return;const sameTarget=a.assignment&&b.assignment&&a.assignment.taskId===b.assignment.taskId&&a.assignment.targetId===b.assignment.targetId;if(sameTarget&&this.state.turn%2===0)this.adjustCrewRelation(a.id,b.id,1,'Gemeinsamer Dauerauftrag');if(a.stress>78&&b.stress>78&&this.state.turn%3===0)this.adjustCrewRelation(a.id,b.id,-1,'Beiderseitiger Stress');});}
    runCrewInteraction(aId,bId,mode='talk'){if(aId===bId)return{ok:false,reason:'Zwei unterschiedliche Personen auswählen.'};const a=this.getMember(aId),b=this.getMember(bId);if(!a||!b)return{ok:false,reason:'Crewmitglied nicht gefunden.'};if((a.injuredUntil&&a.injuredUntil>this.state.turn)||(b.injuredUntil&&b.injuredUntil>this.state.turn))return{ok:false,reason:'Verletzte Crew zuerst erholen lassen.'};const key=pairKey(aId,bId),last=this.state.crewInteractions[key]||-99;if(this.state.turn-last<3)return{ok:false,reason:`Diese beiden brauchen noch ${3-(this.state.turn-last)} Zug/Züge Abstand.`};const defs={talk:{cost:30,delta:5,skill:'social',xp:8,label:'Aussprache'},plan:{cost:45,delta:4,skill:'analysis',xp:9,label:'Gemeinsame Planung'},spar:{cost:25,delta:3,skill:'combat',xp:10,label:'Sparring'}};const def=defs[mode];if(!def)return{ok:false,reason:'Interaktion unbekannt.'};if(this.state.resources.money<def.cost)return{ok:false,reason:'Zu wenig Bargeld.'};this.state.resources.money-=def.cost;this.adjustCrewRelation(aId,bId,def.delta+Math.floor((a.skills.social+b.skills.social)/8),def.label);this.awardMemberSkillXp(aId,def.skill,def.xp,def.label);this.awardMemberSkillXp(bId,def.skill,def.xp,def.label);a.stress=clamp(a.stress+(mode==='spar'?3:-5),0,100);b.stress=clamp(b.stress+(mode==='spar'?3:-5),0,100);a.loyalty=clamp(a.loyalty+1);b.loyalty=clamp(b.loyalty+1);this.state.crewInteractions[key]=this.state.turn;this.state.stats.crewInteractions+=1;this.log('crew',`${a.name} und ${b.name}: ${def.label}.`);this.advanceTurn();return{ok:true,relation:this.getCrewRelation(aId,bId),turn:this.state.turn};}
    getInterior(locationId=this.state.selectedLocationId){const loc=this.getLocation(locationId),defined=this.data.interiorScenes?.[loc.id],fallback=this.data.fallbackInteriors?.[loc.kind]||{title:'Ortsszene',theme:'bunker'};const scene={title:defined?.title||fallback.title,subtitle:defined?.subtitle||`${loc.title} aus der Innenperspektive.`,theme:defined?.theme||fallback.theme,hotspots:defined?.hotspots||[['Lagepunkt','◇','Lokale Informationen und Möglichkeiten.'],['Ausgang','⇢','Zur Stadtkarte zurückkehren.']]};const district=this.getDistrict(locationId),company=this.data.companies.find((c)=>c.locationId===loc.id),assets=this.state.assets.filter((a)=>a.locationId===loc.id);return{...clone(scene),locationId:loc.id,locationTitle:loc.title,owner:this.ownerLabel(district.owner),control:district.control,police:district.police,rival:district.rival,company:company?{name:company.name,price:this.state.market.companies[company.id]?.price}:null,assets:assets.length,events:typeof this.getCityEventsAt==='function'?this.getCityEventsAt(loc.id):[],ambient:this.data.ambientProfiles?.[scene.theme]||this.data.ambientProfiles?.bunker};}
    recordInteriorOpen(locationId=this.state.selectedLocationId){this.state.stats.interiorsOpened+=1;this.log('scene',`Innenansicht geöffnet: ${this.getLocation(locationId).title}.`);return this.getInterior(locationId);}
    acceptMission(missionId){const result=super.acceptMission(missionId);if(result.ok){const mission=this.state.missions.active.find((m)=>m.id===missionId);if(mission)mission.briefingPending=true;}return result;}
    getMissionBriefing(missionId){const mission=this.state.missions.active.find((m)=>m.id===missionId);if(!mission)return null;const skill=relevantSkill(mission.category),crew=[...this.state.gang].sort((a,b)=>(b.skills[skill]||0)-(a.skills[skill]||0)),advisor=crew[0],partner=crew[1];return{mission:clone(mission),skill,advisor:advisor?{id:advisor.id,name:advisor.name,level:advisor.skills[skill]}:null,partner:partner?{id:partner.id,name:partner.name,level:partner.skills[skill]}:null,resolved:!!this.state.missionBriefings[missionId],choice:this.state.missionBriefings[missionId]||null,choices:clone(this.data.briefingChoices||[])};}
    resolveMissionBriefing(missionId,choiceId){const info=this.getMissionBriefing(missionId);if(!info)return{ok:false,reason:'Aktiver Auftrag nicht gefunden.'};if(info.resolved)return{ok:false,reason:'Dieses Briefing wurde bereits entschieden.'};const mission=this.state.missions.active.find((m)=>m.id===missionId),choice=this.data.briefingChoices.find((c)=>c.id===choiceId);if(!choice)return{ok:false,reason:'Entscheidung unbekannt.'};if(choiceId==='careful'){mission.deadline+=2;if(mission.reward?.money)mission.reward.money=Math.round(mission.reward.money*.9);this.state.directorModifiers.tension=clamp(this.state.directorModifiers.tension-6,-30,30);}else if(choiceId==='bold'){mission.deadline=Math.max(this.state.turn+2,mission.deadline-1);if(mission.reward?.money)mission.reward.money=Math.round(mission.reward.money*1.2);this.state.directorModifiers.tension=clamp(this.state.directorModifiers.tension+8,-30,30);this.state.boss.respect=clamp(this.state.boss.respect+1);}else{mission.deadline+=1;this.state.directorModifiers.opportunity=clamp(this.state.directorModifiers.opportunity+6,-30,30);if(info.advisor)this.awardMemberSkillXp(info.advisor.id,info.skill,12,'Missionsbriefing');if(info.partner)this.awardMemberSkillXp(info.partner.id,'social',8,'Missionsbriefing');if(info.advisor&&info.partner)this.adjustCrewRelation(info.advisor.id,info.partner.id,5,'Gemeinsames Missionsbriefing');}
      mission.briefingPending=false;mission.briefingChoice=choiceId;this.state.missionBriefings[missionId]={choiceId,turn:this.state.turn};this.state.stats.briefings+=1;this.log('mission',`Briefing „${mission.title}“: ${choice.title}.`);return{ok:true,mission:clone(mission),choice:clone(choice)};}
    setMapLayer(layer){const allowed=['ownership','pressure','economy','events'];if(!allowed.includes(layer))return{ok:false,reason:'Kartenebene unbekannt.'};this.state.preferences.mapLayer=layer;return{ok:true,layer};}
    setAmbientEnabled(enabled){this.state.preferences.ambient=!!enabled;return{ok:true,enabled:this.state.preferences.ambient};}
    updateDirector(){const base=super.updateDirector(),mods=this.state.directorModifiers||{tension:0,opportunity:0};const next={...base,tension:clamp(base.tension+mods.tension),opportunity:clamp(base.opportunity+mods.opportunity)};this.state.director=next;return clone(next);}
    advanceTurn(joinBoost=0){super.advanceTurn(joinBoost);this.resolveCrewRelations();this.state.directorModifiers.tension=Math.round((this.state.directorModifiers.tension||0)*.65);this.state.directorModifiers.opportunity=Math.round((this.state.directorModifiers.opportunity||0)*.65);}
    finishCombat(outcome){const ids=this.state.combatSession?.crewIds?[...this.state.combatSession.crewIds]:[],result=super.finishCombat(outcome);if(result?.ok&&ids.length){for(let i=0;i<ids.length;i+=1){const m=this.getMember(ids[i]);if(m){m.stress=clamp(m.stress+(outcome==='win'?5:outcome==='loss'?12:7),0,100);m.morale=clamp(m.morale+(outcome==='win'?5:outcome==='loss'?-8:-2),0,100);}for(let j=i+1;j<ids.length;j+=1)this.adjustCrewRelation(ids[i],ids[j],outcome==='win'?5:outcome==='loss'?2:1,`Gemeinsamer Kampf: ${outcome}`);}}return result;}
    getDecisionSupport(){const base=super.getDecisionSupport(),avgStress=Math.round(this.state.gang.reduce((s,m)=>s+m.stress,0)/Math.max(1,this.state.gang.length)),weak=this.getCrewRelationsOverview().filter((r)=>r.value<34).length;const warnings=[...base.warnings];if(avgStress>=65)warnings.unshift(`Crew-Stress hoch: Ø ${avgStress}/100.`);if(weak)warnings.unshift(`${weak} angespannte Crew-Beziehung${weak===1?'':'en'} beachten.`);return{...base,avgStress,relationshipWarnings:weak,warnings:warnings.slice(0,6)};}
  }
  return{...BASE,GameEngine:LivingCity05Engine,LivingCity05Engine};
});
