(function(root){
  'use strict';
  const engine=root.GAME_ENGINE||root.LIVING_CITY_08_ENGINE;if(!engine)return;
  const $=(s)=>document.querySelector(s),esc=(v)=>String(v??'').replace(/[&<>"']/g,(m)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  let lastEchoId=null;
  function persist(){try{const raw=engine.exportState();['pppoppi-bunkerwahrheit-html-v0140','pppoppi-bunkerwahrheit-html-v0130','pppoppi-bunkerwahrheit-html-v0120'].forEach((k)=>localStorage.setItem(k,raw));}catch(_){} }
  function ensureShell(){
    const actions=$('.top-actions');if(actions&&!$('#lc08JournalButton')){const b=document.createElement('button');b.className='btn ghost';b.id='lc08JournalButton';b.title='Entscheidungsjournal öffnen (Taste J)';b.textContent='Journal';actions.insertBefore(b,$('#helpButton'));}
    if(!$('#lc08JournalDialog')){const d=document.createElement('dialog');d.id='lc08JournalDialog';d.className='modal lc08-journal-modal';d.innerHTML='<div class="modal-card wide lc08-journal-card"><button class="modal-close" data-lc08-close aria-label="Journal schließen">×</button><div id="lc08JournalContent"></div></div>';document.body.appendChild(d);}
    if(!$('#lc08Live')){const live=document.createElement('div');live.id='lc08Live';live.className='sr-only';live.setAttribute('aria-live','polite');live.setAttribute('aria-atomic','true');document.body.appendChild(live);}
  }
  function arcCard(arc){const current=arc.currentStage;return`<article class="lc08-arc ${arc.complete?'complete':''}"><div class="lc08-arc-head"><span>${esc(arc.icon||'◇')}</span><div><b>${esc(arc.title)}</b><small>${arc.complete?'Abgeschlossen':current?esc(current.title):'In Arbeit'}</small></div><strong>${arc.done}/${arc.total}</strong></div><div class="lc08-progress"><i style="width:${arc.progress}%"></i></div><p>${arc.complete?'Dieser Entwicklungsbogen wirkt dauerhaft als abgeschlossene Linie weiter.':esc(current?.hint||arc.description)}</p></article>`;}
  function journalRow(entry){const label=engine.data.journalLabels?.[entry.kind]||entry.kind;return`<article class="lc08-journal-row"><span>${esc(label)} · Zug ${entry.turn}</span><b>${esc(entry.title)}</b><p>${esc(entry.detail)}</p></article>`;}
  function renderJournal(){
    const box=$('#lc08JournalContent');if(!box)return;const summary=engine.getStorySummary(),arcs=summary.arcs||[],pending=summary.pending||[],entries=engine.getDecisionJournal(16);
    box.innerHTML=`<header class="lc08-journal-head"><div><span class="eyebrow">STADTGEDÄCHTNIS</span><h2>Entscheidungen und spätere Folgen</h2><p>Hier siehst du nicht nur <b>was</b> passiert ist, sondern welche frühere Entscheidung später wieder wirkt.</p></div><div class="lc08-journal-kpis"><span><b>${summary.count}</b> Linien</span><span><b>${entries.length}</b> jüngste Einträge</span><span><b>${pending.length}</b> offene Folgen</span></div></header><section class="lc08-arc-grid" aria-label="Entwicklungsbögen">${arcs.map(arcCard).join('')}</section><section class="lc08-memory-grid"><div><h3>Folgen in Vorbereitung</h3>${pending.length?pending.slice(0,6).map((x)=>`<article class="lc08-pending"><span>wirkt in ${Math.max(0,x.dueTurn-engine.state.turn)} Zug/Zügen</span><b>${esc(x.title)}</b><p>${esc(x.detail)}</p></article>`).join(''):'<p class="muted">Aktuell wartet keine verzögerte Folge.</p>'}</div><div><h3>Entscheidungsjournal</h3>${entries.length?entries.map(journalRow).join(''):'<p class="muted">Die nächsten wichtigen Entscheidungen werden hier nachvollziehbar gesammelt.</p>'}</div></section><footer class="lc08-journal-foot">Taste <kbd>J</kbd> öffnet oder schließt dieses Journal. Das Spiel läuft dabei nicht weiter.</footer>`;
  }
  function toggleJournal(force){ensureShell();const d=$('#lc08JournalDialog');if(!d)return;const open=typeof force==='boolean'?force:!d.open;if(open){renderJournal();if(!d.open)d.showModal();setTimeout(()=>d.querySelector('[data-lc08-close]')?.focus(),0);}else if(d.open)d.close();}
  function decorateStoryStrip(){
    const strip=$('#lc07StoryStrip');if(!strip)return;let chip=strip.querySelector('.lc08-memory-chip');if(!chip){chip=document.createElement('button');chip.className='mini-btn lc08-memory-chip';chip.type='button';chip.dataset.lc08Journal='1';strip.appendChild(chip);}const arcs=engine.getStoryArcs(),active=arcs.find((a)=>!a.complete);chip.textContent=active?`Bogen ${active.done}/${active.total}`:`${arcs.length}/${arcs.length} Bögen`;chip.title=active?`${active.title}: ${active.currentStage?.title||'in Arbeit'}`:'Alle Entwicklungsbögen abgeschlossen';
  }
  function augmentHelp(){const body=$('#helpDockBody');if(!body||body.querySelector('.lc08-help-extra'))return;const extra=document.createElement('article');extra.className='help-step lc08-help-extra';extra.innerHTML='<strong>LC08 · Stadtgedächtnis</strong><p>Frühere Entscheidungen können einige Züge später erneut wirken. Das Journal erklärt die Kette und zeigt Entwicklungsbögen.</p><div class="key-grid"><span><kbd>J</kbd>Journal</span><span><kbd>G</kbd>nächster Schritt</span><span><kbd>I</kbd>Innenraum</span><span><kbd>K</kbd>Klang</span></div>';body.appendChild(extra);}
  function announceEcho(){const echo=(engine.getStorySummary().consequences||[]).find((x)=>x.kind==='echo');if(!echo||echo.id===lastEchoId)return;const id=`${echo.turn}|${echo.title}`;if(id===lastEchoId)return;lastEchoId=id;const live=$('#lc08Live');if(live)live.textContent=`Späte Folge: ${echo.title}. ${echo.detail}`;}
  function render(){ensureShell();decorateStoryStrip();augmentHelp();if($('#lc08JournalDialog')?.open)renderJournal();announceEcho();}
  document.addEventListener('click',(e)=>{const t=e.target.closest?.('#lc08JournalButton,[data-lc08-journal],[data-lc08-close]');if(!t)return;if(t.matches('[data-lc08-close]'))toggleJournal(false);else toggleJournal();});
  document.addEventListener('keydown',(e)=>{if(e.ctrlKey||e.metaKey||e.altKey||['INPUT','TEXTAREA','SELECT'].includes(e.target?.tagName))return;if(e.key.toLowerCase()==='j'){e.preventDefault();toggleJournal();}});
  document.addEventListener('click',(e)=>{if(e.target.closest?.('[data-dialogue-choice],[data-lc06-interior-action],[data-travel-to],[data-combat-decision]'))setTimeout(()=>{render();persist();},0);},true);
  root.LIVING_CITY_08_UI=Object.freeze({render,toggleJournal,renderJournal});
  render();
})(typeof globalThis!=='undefined'?globalThis:this);
