(function(root){
  'use strict';
  const engine=root.LIVING_CITY_10_ENGINE||root.LIVING_CITY_09_ENGINE,storage=root.LIVING_CITY_10_STORAGE;if(!engine||!storage)return;
  const $=(s)=>document.querySelector(s),esc=(v)=>String(v??'').replace(/[&<>"']/g,(m)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  function persist(){try{const raw=engine.exportState();[storage.newKey,storage.previousKey,...storage.olderKeys].forEach((k)=>localStorage.setItem(k,raw));$('#saveStatus')?.replaceChildren(document.createTextNode('LC10 lokal gespeichert'));}catch(error){console.warn(error);}}
  function trendClass(n){return n>=3?'up':n<=-3?'down':'flat';}
  function trendMarkup(){
    const city=engine.getCityTrends();
    return `<section class="lc10-summary"><article><span>Höchster Druck</span><b>${esc(city.pressure.title)}</b><small>${city.pressure.pressure}/100 · ${esc(city.pressure.band.label)}</small></article><article><span>Beste Dynamik</span><b>${esc(city.improving.title)}</b><small class="${trendClass(city.improving.momentum)}">${city.improving.momentum>0?'+':''}${city.improving.momentum} Momentum</small></article><article><span>Offene Crew-Impulse</span><b>${engine.getCrewInitiatives().length}</b><small>frei entscheidbar</small></article></section><section class="lc10-districts">${city.districts.map((d)=>`<article class="lc10-district"><header><div><b>${esc(d.title)}</b><small>${esc(d.owner)} · ${esc(d.band.label)}</small></div><strong class="${trendClass(d.momentum)}">${d.momentum>0?'+':''}${d.momentum}</strong></header><div class="lc10-bars"><label>Druck <i><span style="width:${d.pressure}%"></span></i><b>${d.pressure}</b></label><label>Stabilität <i><span style="width:${d.stability}%"></span></i><b>${d.stability}</b></label><label>Chancen <i><span style="width:${d.opportunity}%"></span></i><b>${d.opportunity}</b></label></div><p>${esc(d.lastReason)}</p></article>`).join('')}</section>`;
  }
  function initiativeMarkup(){const list=engine.getCrewInitiatives();return `<section class="lc10-initiatives"><div class="lc10-section-head"><div><span>CREW-EIGENINITIATIVE</span><b>Die Crew reagiert selbst auf die Stadt</b></div></div>${list.length?list.map((x)=>`<article><div><b>${esc(x.memberName)} · ${esc(x.title)}</b><small>${esc(x.locationTitle)}</small><p>${esc(x.detail)}</p></div><div class="lc10-choice-row">${x.choices.map((c)=>`<button class="mini-btn" data-lc10-initiative="${esc(x.id)}" data-lc10-choice="${esc(c.id)}" title="${esc(c.description)}">${esc(c.title)}</button>`).join('')}</div></article>`).join(''):'<p class="muted">Aktuell wartet keine Crew-Initiative auf eine Entscheidung.</p>'}</section>`;}
  function historyMarkup(){const h=engine.getCityTrends().history;return `<section class="lc10-history"><div class="lc10-section-head"><div><span>WARUM HAT SICH ETWAS VERÄNDERT?</span><b>Letzte Stadtbewegungen</b></div></div>${h.length?h.map((x)=>`<article><b>Zug ${x.turn} · ${esc(x.reason)}</b><small>${x.changes.map((c)=>`${esc(engine.getLocation(c.locationId).short)} ${c.momentum>0?'+':''}${c.momentum}`).join(' · ')}</small></article>`).join(''):'<p class="muted">Noch keine deutliche Trendänderung gespeichert.</p>'}</section>`;}
  function render(){const body=$('#lc10CityBody');if(body)body.innerHTML=trendMarkup()+initiativeMarkup()+historyMarkup();}
  function ensureUI(){
    if(!$('#lc10CityButton')){const b=document.createElement('button');b.className='btn ghost';b.id='lc10CityButton';b.textContent='Stadtlage';b.title='Bezirksentwicklung und Crew-Initiativen · Taste L';$('#lc09HubButton')?.insertAdjacentElement('afterend',b);}
    if(!$('#lc10CityDialog')){const d=document.createElement('dialog');d.id='lc10CityDialog';d.className='modal lc10-city-modal';d.innerHTML='<div class="modal-card wide lc10-city-card"><button class="modal-close" data-lc10-close aria-label="Stadtlage schließen">×</button><span class="eyebrow">LIVING-CITY-10</span><h2>Stadtlage</h2><p class="muted">Trends zeigen Richtung statt nur Momentwerte. Details erscheinen nur hier und belasten die Hauptansicht nicht.</p><div id="lc10CityBody"></div></div>';document.body.appendChild(d);}
  }
  document.addEventListener('click',(e)=>{const t=e.target.closest?.('#lc10CityButton,[data-lc10-close],[data-lc10-initiative]');if(!t)return;if(t.id==='lc10CityButton'){render();$('#lc10CityDialog').showModal();return;}if(t.hasAttribute('data-lc10-close')){$('#lc10CityDialog').close();return;}if(t.dataset.lc10Initiative){const r=engine.resolveCrewInitiative(t.dataset.lc10Initiative,t.dataset.lc10Choice);if(r.ok){persist();render();root.GAME_UI_REFRESH?.schedule?.();$('#tickerText').textContent=`${r.initiative.memberName}: ${r.choice.title}. Stadtlage wurde aktualisiert.`;}else $('#tickerText').textContent=r.reason;}});
  document.addEventListener('keydown',(e)=>{if(e.ctrlKey||e.metaKey||e.altKey||['INPUT','SELECT','TEXTAREA'].includes(e.target?.tagName))return;const k=e.key.toLowerCase();if(k==='g'){e.preventDefault();root.LIVING_CITY_06_UI?.renderGuide?.();const box=$('#focusDashboard'),target=box?.querySelector('.lc06-guide-card button');if(target)target.focus();else if(box){if(!box.hasAttribute('tabindex'))box.setAttribute('tabindex','-1');box.focus();}return;}if(e.key.toLowerCase()==='l'&&!document.querySelector('dialog[open]')){e.preventDefault();render();$('#lc10CityDialog').showModal();}});
  ensureUI();document.body.dataset.livingCity='10';root.LIVING_CITY_10_UI=Object.freeze({render});
})(typeof globalThis!=='undefined'?globalThis:this);
