(function(root){
  'use strict';
  const engine=root.LIVING_CITY_11_ENGINE||root.LIVING_CITY_10_ENGINE,storage=root.LIVING_CITY_11_STORAGE;if(!engine||!storage)return;
  const $=(s)=>document.querySelector(s),esc=(v)=>String(v??'').replace(/[&<>'"]/g,(m)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
  const money=(v)=>`${Number(v||0).toLocaleString('de-DE',{maximumFractionDigits:0})} €`;
  let activeView='overview',selectedMember=engine.state.gang[0]?.id||'',selectedArt=engine.data.martialArts?.[0]?.id||'',selectedProgram='standard';
  function persist(){try{const raw=engine.exportState();[storage.newKey,storage.previousKey,...storage.olderKeys].forEach((k)=>localStorage.setItem(k,raw));$('#saveStatus')?.replaceChildren(document.createTextNode('LC11 lokal gespeichert'));}catch(error){console.warn(error);}}
  function notify(text){const el=$('#tickerText');if(el)el.textContent=text;}
  function button(id,label,view){return `<button class="lc11-nav ${activeView===view?'active':''}" data-lc11-view="${view}" id="${id}">${label}</button>`;}
  function summaryMarkup(){const s=engine.getLivingCity11Summary(),loc=engine.getCurrentLocation();return `<section class="lc11-overview-grid"><article class="lc11-feature casino"><span>CASINO</span><b>${s.casino.session.spins} Drehungen · ${s.casino.session.pokerHands} Poker</b><small>${esc(s.casino.lastResult)}</small><button data-lc11-view="casino">Casino betreten</button></article><article class="lc11-feature training"><span>TRAINING</span><b>${s.training.crew.length} Crewmitglieder</b><small>${s.training.available?'Dojo ist am aktuellen Ort verfügbar.':'Reise in die Ostblöcke zum Dojo.'}</small><button data-lc11-view="training">Training öffnen</button></article><article class="lc11-feature gear"><span>SCHUTZ & AUSRÜSTUNG</span><b>${s.protection.items.length} Gegenstände</b><small>${s.protection.available?'Eisenladen und Wartung sind verfügbar.':'Reise zum Schwarzmarkt.'}</small><button data-lc11-view="gear">Ausrüstung öffnen</button></article><article class="lc11-feature station"><span>BAHNHOF</span><b>${s.station.destinations.length} Fernziele</b><small>${s.station.available?`Ticket-Rabatt ${s.station.discount}%`:'Fernreisen starten am Geisterbahnhof.'}</small><button data-lc11-view="station">Abfahrtstafel</button></article></section><section class="lc11-current-scene"><span>AKTUELLER ORT</span><h3>${esc(loc.title)}</h3><p>${esc(loc.description)}</p></section>`;}
  function casinoMarkup(){
    const floor=engine.getCasinoFloor(),here=engine.getCurrentLocation().kind==='casino',p=engine.state.casino.poker;
    if(!here)return `<section class="lc11-empty"><b>Casino 9909 ist nicht dein aktueller Standort.</b><p>Reise dorthin über die Karte oder vom Geisterbahnhof mit der Nachtlinie 9.</p></section>`;
    const slots=engine.data.casino.slotMachines.map((m)=>{const last=engine.state.casino.lastSlot?.machineId===m.id?engine.state.casino.lastSlot:null,j=floor.jackpots[m.id]||0;return `<article class="lc11-slot" data-machine="${m.id}"><header><div><span>AUTOMAT</span><b>${esc(m.title)}</b></div><strong>Jackpot ${money(j)}</strong></header><div class="lc11-reels">${(last?.reels||['7','★','BAR']).map((r)=>`<i>${esc(r)}</i>`).join('')}</div><div class="lc11-control-row"><input id="lc11-bet-${m.id}" type="number" min="${m.minBet}" max="${m.maxBet}" value="${m.minBet}" aria-label="Einsatz ${esc(m.title)}"><button data-lc11-spin="${m.id}">Drehen</button></div><small>${esc(m.volatility)} · ${m.minBet}–${m.maxBet} € Einsatz</small></article>`;}).join('');
    let poker='';
    if(!p||p.status==='finished')poker=`<section class="lc11-poker"><header><div><span>5-CARD DRAW</span><h3>Poker-Tisch</h3></div><strong>Bargeld ${money(engine.state.resources.money)}</strong></header>${p?.result?`<div class="lc11-result">${esc(p.result.result)} · ${esc(p.result.playerRank)} gegen ${esc(p.result.dealerRank)} · Auszahlung ${money(p.result.payout)}</div>`:''}<div class="lc11-control-row"><input id="lc11PokerBet" type="number" min="10" max="500" value="50"><button data-lc11-poker-start>Neue Hand</button></div></section>`;
    else poker=`<section class="lc11-poker active"><header><div><span>DEIN BLATT</span><h3>Einsatz ${money(p.bet)}</h3></div><strong>Ziehrunde ${p.draws}/2</strong></header><p>Nicht gehaltene Karten werden beim Ziehen ersetzt.</p><div class="lc11-cards">${p.player.map((c,i)=>`<button class="${p.holds[i]?'held':''} ${c.s==='♥'||c.s==='♦'?'red':''}" data-lc11-poker-hold="${i}"><b>${esc(c.r)}</b><span>${esc(c.s)}</span><small>${p.holds[i]?'GEHALTEN':'TAUSCHEN'}</small></button>`).join('')}</div><div class="lc11-control-row"><button data-lc11-poker-draw ${p.draws>=2?'disabled':''}>Karten ziehen</button><button class="primary" data-lc11-poker-finish>Showdown</button></div></section>`;
    const challenges=floor.challenges.map((c)=>`<article class="lc11-challenge ${c.complete?'complete':''}"><div><b>${esc(c.title)}</b><small>${esc(c.description)} · ${Math.min(c.progress,c.target)}/${c.target}</small></div><button data-lc11-claim="${c.id}" ${!c.complete||c.claimed?'disabled':''}>${c.claimed?'Abgeholt':`+${c.reward} €`}</button></article>`).join('');
    return `<section class="lc11-casino-head"><div><span>CASINO 9909</span><h3>Spielhalle</h3></div><div><b>Session ${floor.session.net>=0?'+':''}${money(floor.session.net)}</b><small>Serie ${floor.streak}</small></div></section><div class="lc11-slots">${slots}</div>${poker}<section class="lc11-challenges"><h3>Casino-Aufgaben</h3>${challenges}<button class="subtle" data-lc11-session-reset>Session zurücksetzen</button></section>`;
  }
  function trainingMarkup(){
    const center=engine.getTrainingCenter();if(!center.available)return `<section class="lc11-empty"><b>Das Dojo liegt in den Ostblöcken.</b><p>Reise zum Wohnbezirk, um Kampfsportarten mit Rang- und Fortschrittswert zu trainieren.</p></section>`;
    const member=center.crew.find((m)=>m.id===selectedMember)||center.crew[0];if(member)selectedMember=member.id;
    const art=center.arts.find((a)=>a.id===selectedArt)||center.arts[0];if(art)selectedArt=art.id;
    const learned=member?.arts.find((a)=>a.artId===selectedArt),program=center.programs.find((p)=>p.id===selectedProgram)||center.programs[1];
    return `<section class="lc11-training-stage"><div class="lc11-training-hero"><span>DOJO OSTBLOCK</span><h3>${esc(member?.name||'Crew wählen')}</h3><p>Belastung ${member?.stress||0}/100 · Macht ${member?.power||0} · ${esc(art?.title||'Training')} Rang ${learned?.rank||0}</p><div class="lc11-progress"><i style="width:${learned?.progress||0}%"></i></div></div><div class="lc11-form-grid"><label>Crew<select id="lc11Member">${center.crew.map((m)=>`<option value="${m.id}" ${m.id===selectedMember?'selected':''}>${esc(m.name)} · Stress ${m.stress}</option>`).join('')}</select></label><label>Kampfsport<select id="lc11Art">${center.arts.map((a)=>`<option value="${a.id}" ${a.id===selectedArt?'selected':''}>${esc(a.title)}</option>`).join('')}</select></label><label>Einheit<select id="lc11Program">${center.programs.map((p)=>`<option value="${p.id}" ${p.id===selectedProgram?'selected':''}>${esc(p.title)} · ${esc(p.description)}</option>`).join('')}</select></label></div><div class="lc11-training-summary"><b>Kosten ca. ${money(Math.round((art?.cost||0)*(program?.costFactor||1)))}</b><span>Praxisfaktor ×${program?.xpFactor||1} · Stress +${program?.stress||0}</span><button class="primary" data-lc11-train>Training starten</button></div></section><section class="lc11-history-list"><h3>Letzte Einheiten</h3>${center.history.length?center.history.map((h)=>`<article><b>Z${h.turn} · ${esc(h.memberName)}</b><span>${esc(h.artTitle)} · ${esc(h.programTitle)} · Rang ${h.rank} (${h.progress}%)</span></article>`).join(''):'<p>Noch keine LC11-Trainingseinheit.</p>'}</section>`;
  }
  function gearMarkup(){
    const center=engine.getProtectionCenter();if(!center.available)return `<section class="lc11-empty"><b>Schutzkleidung und Wartung gibt es am Schwarzmarkt.</b><p>Im Eisenladen kannst du Gegenstände kaufen, einer Crew zuweisen und ihren Zustand wiederherstellen.</p></section>`;
    const crew=engine.state.gang.filter((m)=>m.status!=='left');
    const catalog=center.catalog.map((g)=>`<article class="lc11-gear-card"><div class="lc11-gear-icon">${g.type==='protection'?'◆':g.type==='training'?'◎':'◇'}</div><div><b>${esc(g.title)}</b><small>${esc(g.description)}</small><div class="lc11-tags"><span>Schutz +${g.defenseBonus||0}</span><span>Kampf +${g.combatBonus||0}</span><span>Analyse +${g.analysisBonus||0}</span></div></div><button data-lc11-buy-gear="${g.id}">${money(g.cost)}</button></article>`).join('');
    const owned=center.items.length?center.items.map((i)=>`<article class="lc11-owned-gear"><div><b>${esc(i.title)}</b><small>Zustand ${i.condition}% · ${i.equippedBy?`bei ${esc(engine.getMember(i.equippedBy)?.name||'?')}`:'nicht ausgerüstet'}</small><div class="lc11-condition"><i style="width:${i.condition}%"></i></div></div><div class="lc11-gear-actions"><select data-lc11-equip-select="${i.id}"><option value="">Crew wählen</option>${crew.map((m)=>`<option value="${m.id}">${esc(m.name)}</option>`).join('')}</select><button data-lc11-equip="${i.id}">Ausrüsten</button><button data-lc11-service="${i.id}" ${i.condition>=100?'disabled':''}>Warten</button></div></article>`).join(''):'<p>Noch keine Ausrüstung im Inventar.</p>';
    return `<section class="lc11-gear-section"><div class="lc11-section-title"><div><span>EISENLADEN</span><h3>Schutz & Ausrüstung</h3></div><strong>${money(engine.state.resources.money)}</strong></div><div class="lc11-gear-grid">${catalog}</div></section><section class="lc11-owned"><h3>Inventar & Zustand</h3>${owned}</section>`;
  }
  function stationMarkup(){
    const board=engine.getIntercityBoard();if(!board.available)return `<section class="lc11-empty"><b>Fernlinien starten am Geisterbahnhof.</b><p>Reise zum Bahnhof. Dort werden andere Städte als eigenständige Ausflüge mit Kosten, Dauer und Rückkehr abgewickelt.</p></section>`;
    const cards=board.destinations.map((d)=>`<article class="lc11-destination"><div class="lc11-train-line"><i></i><span>${d.duration} Züge</span></div><div><span>${esc(d.subtitle)}</span><h3>${esc(d.title)}</h3><p>${esc(d.description)}</p><div class="lc11-tags"><b>${money(d.cost)}</b>${Object.entries(d.reward||{}).map(([k,v])=>`<span>${esc(({money:'Geld',influence:'Einfluss',analysisXp:'Analyse-XP',supplies:'Vorrat',combatXp:'Kampf-XP',enduranceXp:'Ausdauer-XP',respect:'Respekt',socialXp:'Sozial-XP',intel:'Aufklärung',drivingXp:'Fahr-XP'})[k]||k)} +${v}</span>`).join('')}</div></div><button data-lc11-trip="${d.id}">Ticket & Reise</button></article>`).join('');
    const history=board.history.length?board.history.map((h)=>`<article><b>${esc(h.title)}</b><span>Z${h.turn} · ${h.duration} Züge · ${money(h.cost)}</span></article>`).join(''):'<p>Noch keine Fernreise.</p>';
    return `<section class="lc11-station-head"><div><span>GEISTERBAHNHOF</span><h3>Fernlinien</h3></div><strong>Rabatt ${board.discount}%</strong></section><div class="lc11-destinations">${cards}</div><section class="lc11-history-list"><h3>Reisehistorie</h3>${history}</section>`;
  }
  function bodyMarkup(){if(activeView==='casino')return casinoMarkup();if(activeView==='training')return trainingMarkup();if(activeView==='gear')return gearMarkup();if(activeView==='station')return stationMarkup();return summaryMarkup();}
  function render(){
    if(!$('#lc11ContextDock')&&$('#districtPanel')){const box=document.createElement('section');box.id='lc11ContextDock';box.className='lc11-context-dock';$('#districtPanel').appendChild(box);}
    const body=$('#lc11Body');if(body){body.dataset.view=activeView;body.innerHTML=bodyMarkup();}const card=$('.lc11-card');if(card)card.dataset.view=activeView;
    const dock=$('#lc11ContextDock');if(dock){const kind=engine.getCurrentLocation().kind,map={casino:['Casino spielen','casino'],residential:['Dojo öffnen','training'],market:['Eisenladen öffnen','gear'],station:['Fernlinien öffnen','station']}[kind];dock.innerHTML=map?`<button data-lc11-open data-lc11-start-view="${map[1]}"><span>LC11</span><b>${map[0]}</b><small>animierte Vollansicht</small></button>`:`<button data-lc11-open><span>LC11</span><b>Stadtleben</b><small>Casino · Training · Schutz · Bahn</small></button>`;}
  }
  function open(view){activeView=view||'overview';engine.registerInteriorVisit();render();const d=$('#lc11Dialog');if(!d.open)d.showModal();}
  function ensureUI(){
    if(!$('#lc11Button')){const b=document.createElement('button');b.className='btn primary lc11-launch';b.id='lc11Button';b.textContent='Stadtleben';b.title='Casino, Training, Schutz und Fernreisen · Taste V';$('#lc10CityButton')?.insertAdjacentElement('afterend',b);}
    if(!$('#lc11ContextDock')){const box=document.createElement('section');box.id='lc11ContextDock';box.className='lc11-context-dock';$('#districtPanel')?.appendChild(box);}
    if(!$('#lc11Dialog')){const d=document.createElement('dialog');d.id='lc11Dialog';d.className='modal lc11-modal';d.innerHTML=`<div class="modal-card wide lc11-card"><button class="modal-close" data-lc11-close aria-label="Stadtleben schließen">×</button><header class="lc11-header"><div><span class="eyebrow">LIVING-CITY-11</span><h2>Stadtleben</h2><p>Spielbare Orte, sichtbarer Fortschritt und stärkere Inszenierung – ohne zusätzliche Dauerflächen.</p></div><div class="lc11-version">0.17.6 · Schema 12</div></header><nav class="lc11-navbar">${button('lc11Overview','Übersicht','overview')}${button('lc11Casino','Casino','casino')}${button('lc11Training','Training','training')}${button('lc11Gear','Schutz','gear')}${button('lc11Station','Bahnhof','station')}</nav><main id="lc11Body"></main></div>`;document.body.appendChild(d);}
  }
  document.addEventListener('change',(e)=>{if(e.target.id==='lc11Member'){selectedMember=e.target.value;render();}if(e.target.id==='lc11Art'){selectedArt=e.target.value;render();}if(e.target.id==='lc11Program'){selectedProgram=e.target.value;render();}});
  document.addEventListener('click',(e)=>{
    const t=e.target.closest?.('[data-lc11-open],#lc11Button,[data-lc11-close],[data-lc11-view],[data-lc11-spin],[data-lc11-poker-start],[data-lc11-poker-hold],[data-lc11-poker-draw],[data-lc11-poker-finish],[data-lc11-claim],[data-lc11-session-reset],[data-lc11-train],[data-lc11-buy-gear],[data-lc11-equip],[data-lc11-service],[data-lc11-trip]');if(!t)return;
    if(t.matches('[data-lc11-open],#lc11Button')){open(t.dataset.lc11StartView||'overview');return;}if(t.hasAttribute('data-lc11-close')){$('#lc11Dialog').close();return;}if(t.dataset.lc11View){activeView=t.dataset.lc11View;$('.lc11-nav.active')?.classList.remove('active');document.querySelector(`.lc11-nav[data-lc11-view="${activeView}"]`)?.classList.add('active');render();return;}
    let r=null;
    if(t.dataset.lc11Spin){const bet=Number($(`#lc11-bet-${t.dataset.lc11Spin}`)?.value||0);t.closest('.lc11-slot')?.classList.add('spinning');r=engine.spinSlot(t.dataset.lc11Spin,bet);setTimeout(()=>{render();root.GAME_UI_REFRESH?.schedule?.();},460);}
    else if(t.hasAttribute('data-lc11-poker-start'))r=engine.startPoker(Number($('#lc11PokerBet')?.value||0));
    else if(t.dataset.lc11PokerHold!==undefined)r=engine.togglePokerHold(Number(t.dataset.lc11PokerHold));
    else if(t.hasAttribute('data-lc11-poker-draw'))r=engine.drawPoker();
    else if(t.hasAttribute('data-lc11-poker-finish'))r=engine.finishPoker();
    else if(t.dataset.lc11Claim)r=engine.claimCasinoChallenge(t.dataset.lc11Claim);
    else if(t.hasAttribute('data-lc11-session-reset'))r=engine.resetCasinoSession();
    else if(t.hasAttribute('data-lc11-train'))r=engine.trainMemberProgram(selectedMember,selectedArt,selectedProgram);
    else if(t.dataset.lc11BuyGear)r=engine.buyGear(t.dataset.lc11BuyGear);
    else if(t.dataset.lc11Equip){const memberId=document.querySelector(`[data-lc11-equip-select="${t.dataset.lc11Equip}"]`)?.value;r=memberId?engine.equipGear(t.dataset.lc11Equip,memberId):{ok:false,reason:'Bitte zuerst Crew wählen.'};}
    else if(t.dataset.lc11Service)r=engine.serviceGear(t.dataset.lc11Service);
    else if(t.dataset.lc11Trip)r=engine.takeIntercityTrip(t.dataset.lc11Trip);
    if(r){if(r.ok){persist();notify('LC11-Aktion ausgeführt.');render();root.GAME_UI_REFRESH?.schedule?.();}else notify(r.reason||'Aktion nicht möglich.');}
  });
  document.addEventListener('keydown',(e)=>{if(e.ctrlKey||e.metaKey||e.altKey||['INPUT','SELECT','TEXTAREA'].includes(e.target?.tagName))return;if(e.key.toLowerCase()==='v'&&!document.querySelector('dialog[open]')){e.preventDefault();open('overview');}});
  ensureUI();render();document.body.dataset.livingCity='11';root.LIVING_CITY_11_UI=Object.freeze({render,open});
})(typeof globalThis!=='undefined'?globalThis:this);
