(function(root,factory){
  const BASE=typeof module==='object'&&module.exports?require('./engine.js'):root.GAME_ENGINE;
  const methods=factory(BASE);
  if(typeof module==='object'&&module.exports)module.exports=methods;else root.REVIVAL_WORLD_METHODS=methods;
})(typeof globalThis!=='undefined'?globalThis:this,function(BASE){
  'use strict';
  const {clamp}=BASE,deepClone=(value)=>JSON.parse(JSON.stringify(value));
  return {
    createInitialRivalRelations(){const ids=this.data.rivalGangs.map((r)=>r.id),out={};for(let i=0;i<ids.length;i+=1)for(let j=i+1;j<ids.length;j+=1)out[this.relationKey(ids[i],ids[j])]=i===0&&j===2?-35:i===0?-20:8;return out;},
    relationKey(a,b){return[a,b].sort().join('|');},
    getRivalRelation(a,b){if(a===b)return 100;return Number(this.state.rivalRelations?.[this.relationKey(a,b)]||0);},
    adjustRivalRelation(a,b,delta,reason='Stadtdynamik'){if(!a||!b||a===b)return 100;const key=this.relationKey(a,b),before=this.getRivalRelation(a,b),next=Math.max(-100,Math.min(100,Math.round(before+delta)));this.state.rivalRelations[key]=next;const crossed=(before>-60&&next<=-60)||(before<55&&next>=55);if(crossed)this.log('relation',`${this.getRivalDefinition(a)?.name||a} / ${this.getRivalDefinition(b)?.name||b}: ${this.getRivalRelationLabel(next)} (${reason}).`);return next;},
    getRivalRelationLabel(value){if(value<=-60)return'Offener Krieg';if(value<=-25)return'Feindschaft';if(value<20)return'Kühle Distanz';if(value<55)return'Zweckkontakt';return'Pakt';},
    getRivalRelationsOverview(){const ids=this.data.rivalGangs.map((r)=>r.id),out=[];for(let i=0;i<ids.length;i+=1)for(let j=i+1;j<ids.length;j+=1){const value=this.getRivalRelation(ids[i],ids[j]);out.push({a:ids[i],b:ids[j],aName:this.getRivalDefinition(ids[i])?.name,bName:this.getRivalDefinition(ids[j])?.name,value,label:this.getRivalRelationLabel(value)});}return out;},
    getRivalWarTarget(rivalId){const wars=this.data.rivalGangs.map((r)=>r.id).filter((id)=>id!==rivalId&&this.getRivalRelation(rivalId,id)<=-60);return wars.sort((a,b)=>this.getRivalRelation(rivalId,a)-this.getRivalRelation(rivalId,b))[0]||null;},
    getCityPhase(){const phases=[{key:'night',label:'Nacht',note:'Licht, Risiko und Nachtökonomie dominieren.'},{key:'dawn',label:'Morgengrauen',note:'Die Stadt wird ruhiger, Bewegungen werden sichtbarer.'},{key:'day',label:'Tag',note:'Wirtschaft und Institutionen arbeiten auf voller Last.'},{key:'evening',label:'Abend',note:'Chancen und Konflikte bauen sich gleichzeitig auf.'}];return phases[(this.state.turn-1)%phases.length];},
    getPrestigeScore(){return Math.round(this.getOwnedDistrictCount()*28+(this.state.stats.missionsCompleted||0)*18+this.state.assets.length*10+this.getInvestmentPortfolio().value/160+(this.state.boss.respect+this.state.boss.influence+this.state.boss.notoriety)*.65);},
    getCityEventDefinition(id){return this.data.cityEvents?.find((event)=>event.id===id)||null;},
    getCityEventsAt(locationId){return this.state.cityEvents.filter((event)=>event.locationId===locationId).map((event)=>({...deepClone(event),definition:deepClone(this.getCityEventDefinition(event.eventId))}));},
    getTravelEventSurcharge(){return this.state.cityEvents.some((event)=>event.eventId==='event.transit.strike')?25:0;},
    spawnCityEvent(force=false,eventId=null,locationId=null){if(!this.data.cityEvents?.length||this.state.cityEvents.length>=2)return null;if(!force&&this.random()>.14)return null;const def=this.getCityEventDefinition(eventId)||this.data.cityEvents[Math.floor(this.random()*this.data.cityEvents.length)],loc=this.getLocation(locationId||this.data.world.locations[Math.floor(this.random()*this.data.world.locations.length)].id),event={id:`city-event-${this.state.turn}-${Math.floor(this.random()*1e6)}`,eventId:def.id,locationId:loc.id,startedTurn:this.state.turn,remaining:def.duration||2};if(def.id==='event.rival.feud'){const ids=this.data.rivalGangs.map((r)=>r.id);event.rivalA=ids[Math.floor(this.random()*ids.length)];event.rivalB=ids.find((id)=>id!==event.rivalA&&this.random()<.6)||ids.find((id)=>id!==event.rivalA);this.adjustRivalRelation(event.rivalA,event.rivalB,def.effects.relation||-18,'Rivalenfehde');}this.state.cityEvents.push(event);this.state.stats.cityEvents+=1;this.log('city-event',`${def.title} in ${loc.title}: ${def.description}`);this.applyCityEventPulse(event,true);return deepClone(event);},
    applyCityEventPulse(event,fresh=false){const def=this.getCityEventDefinition(event.eventId);if(!def)return;const fx=def.effects||{},district=this.getDistrict(event.locationId);['police','unrest','control'].forEach((key)=>{if(Number.isFinite(fx[key]))district[key]=clamp(district[key]+fx[key]);});if(Number.isFinite(fx.intel))district.intel=clamp(district.intel+fx.intel,0,5);if(Number.isFinite(fx.heat))this.state.boss.heat=clamp(this.state.boss.heat+fx.heat);if(Number.isFinite(fx.recruitBoost))this.state.flags.recruitBoost=(this.state.flags.recruitBoost||0)+fx.recruitBoost;if(Number.isFinite(fx.marketMomentum))this.data.companies.filter((c)=>c.locationId===event.locationId).forEach((c)=>{this.state.market.companies[c.id].momentum+=fx.marketMomentum;});if(Number.isFinite(fx.tension))this.state.director.tension=clamp(this.state.director.tension+(fresh?fx.tension:Math.ceil(fx.tension*.2)));if(Number.isFinite(fx.opportunity))this.state.director.opportunity=clamp(this.state.director.opportunity+(fresh?fx.opportunity:Math.ceil(fx.opportunity*.2)));},
    resolveCityEvents(){this.state.cityEvents.forEach((event)=>{this.applyCityEventPulse(event,false);event.remaining-=1;});this.state.cityEvents.filter((event)=>event.remaining<=0).forEach((event)=>this.log('city-event',`${this.getCityEventDefinition(event.eventId)?.title||'Stadtereignis'} in ${this.getLocation(event.locationId).title} endet.`));this.state.cityEvents=this.state.cityEvents.filter((event)=>event.remaining>0);this.spawnCityEvent(false);},
    resolveRivalRelations(){this.getRivalRelationsOverview().forEach((pair)=>{if(this.random()>.24)return;const a=this.getRivalDefinition(pair.a),b=this.getRivalDefinition(pair.b);let delta=Math.floor(this.random()*7)-3;if(a?.strategy==='aggressive'||b?.strategy==='aggressive')delta-=1;if(a?.strategy==='economic'&&b?.strategy==='economic')delta+=2;const next=this.adjustRivalRelation(pair.a,pair.b,delta,'laufende Rivalenpolitik');if(next<=-60&&this.random()<.28){const ra=this.getRivalState(pair.a),rb=this.getRivalState(pair.b);if(ra)ra.wealth=Math.max(0,ra.wealth-45);if(rb)rb.wealth=Math.max(0,rb.wealth-45);if(ra)ra.power=clamp(ra.power-1,10,100);if(rb)rb.power=clamp(rb.power-1,10,100);this.state.stats.rivalWars+=1;this.log('relation',`${pair.aName} und ${pair.bName} verlieren Ressourcen im offenen Konflikt.`);}});},
    getMilestoneValue(def){return this.getObjectiveValue(def.targetKind,def);},
    evaluateMilestones(){this.data.milestones?.forEach((def)=>{if(this.state.milestones.includes(def.id)||this.getMilestoneValue(def)<def.target)return;this.state.milestones.push(def.id);this.applyMissionReward(def.reward);this.log('milestone',`Meilenstein erreicht: ${def.title}.`);});},
    getMilestoneOverview(){return(this.data.milestones||[]).map((def)=>({id:def.id,title:def.title,value:this.getMilestoneValue(def),target:def.target,done:this.state.milestones.includes(def.id),pct:Math.min(100,Math.round(this.getMilestoneValue(def)/Math.max(1,def.target)*100))}));},
    updateDirector(){const districts=Object.values(this.state.districts),avgUnrest=districts.reduce((s,d)=>s+d.unrest,0)/Math.max(1,districts.length),avgRival=districts.reduce((s,d)=>s+d.rival,0)/Math.max(1,districts.length),wars=this.getRivalRelationsOverview().filter((r)=>r.value<=-60).length,tension=clamp(this.state.boss.heat*.34+avgUnrest*.36+avgRival*.2+wars*8+this.state.cityEvents.length*5),opportunity=clamp(28+this.getOwnedDistrictCount()*4+this.state.assets.length*3+Math.min(20,this.getInvestmentPortfolio().value/250)+this.state.missions.offers.length*2-tension*.18);const event=this.state.cityEvents[0],active=this.state.missions.active[0];let headline='Die Stadt wartet auf deine nächste Entscheidung.';if(event)headline=`${this.getCityEventDefinition(event.eventId)?.title||'Stadtereignis'} · ${this.getLocation(event.locationId).title}`;else if(active)headline=`Aktiver Auftrag: ${active.title}`;else if(wars)headline='Rivalengangs befinden sich im offenen Krieg.';this.state.director={tension,opportunity,headline};return deepClone(this.state.director);},
    getDirectorSummary(){const director=this.updateDirector();return{...director,phase:this.getCityPhase(),prestige:this.getPrestigeScore(),events:this.state.cityEvents.map((event)=>({...deepClone(event),definition:deepClone(this.getCityEventDefinition(event.eventId)),locationTitle:this.getLocation(event.locationId).title})),relations:this.getRivalRelationsOverview(),milestones:this.getMilestoneOverview(),missions:this.getMissionOverview()};},
    resolveRivalGangs(){this.state.rivals.forEach((rival)=>{const def=this.getRivalDefinition(rival.id);if(!def||this.random()>.58)return;const warTarget=this.getRivalWarTarget(rival.id);let candidates=this.data.world.locations.filter((location)=>location.id!==this.data.world.startLocationId).map((location)=>({l:location,d:this.getDistrict(location.id)}));if(warTarget&&this.random()<.48){const targets=candidates.filter(({d})=>d.owner===warTarget);if(targets.length)candidates=targets;}if(def.strategy==='aggressive')candidates.sort((a,b)=>(a.d.control-a.d.rival)-(b.d.control-b.d.rival));else if(def.strategy==='economic')candidates.sort((a,b)=>b.l.income-a.l.income);else candidates.sort((a,b)=>(a.d.intel-b.d.intel)+(b.d.unrest-a.d.unrest));const pick=candidates[Math.floor(this.random()*Math.min(4,candidates.length))]||candidates[0];if(!pick)return;const previousOwner=pick.d.owner,push=def.strategy==='aggressive'?7+Math.floor(this.random()*5):4+Math.floor(this.random()*5);pick.d.rival=clamp(pick.d.rival+push);pick.d.rivalGangId=rival.id;if(def.strategy==='aggressive'){pick.d.control=clamp(pick.d.control-Math.ceil(push*.55));pick.d.unrest=clamp(pick.d.unrest+4);rival.power=clamp(rival.power+1,15,100);rival.lastMove=`Drückt offen in ${pick.l.title}.`;}else if(def.strategy==='economic'){const spend=Math.min(rival.wealth,80);rival.wealth-=spend;pick.d.control=clamp(pick.d.control-3);rival.wealth+=45;rival.lastMove=`Kauft Einfluss in ${pick.l.title}.`;}else{pick.d.intel=Math.max(0,pick.d.intel-1);pick.d.unrest=clamp(pick.d.unrest+5);pick.d.police=clamp(pick.d.police+2);rival.lastMove=`Unterwandert ${pick.l.title}.`;}if(previousOwner&&previousOwner!=='neutral'&&previousOwner!=='player'&&previousOwner!==rival.id)this.adjustRivalRelation(rival.id,previousOwner,-3,'Gebietsdruck');this.evaluateTerritoryOwnership(pick.l.id,rival.id);this.state.stats.rivalMoves+=1;this.log('rival',`${def.name}: ${rival.lastMove}`);});}
  };
});
